<?php /* Generated by generate_doc.php from include/lapin/window.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ts_bunny_window@<br />
{<br />
&nbsp;&nbsp;$Tt_bunny_buffer@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbuffer@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tchar@&nbsp;*&nbsp;$Kconst@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sname@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sstyle@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tt_bunny_position@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sposition@;<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_window@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Represents an opened window.<br />
  <br />
  $St_bunny_window@ starts with a $St_bunny_buffer@, so it can be used everywhere a $St_bunny_buffer@ is expected. The buffer contains the width and height of the drawing surface.<br />
  <br />
  A window is opened with $Sbunny_start@ or $Sbunny_start_style@ and closed with $Sbunny_stop@. Windows are write-only from the program point of view: draw into them, then call $Sbunny_display@ to show the result on screen.<br />
</div>
<hr />

<div class="fields">
  <h3>Attributes</h3>
  <ul>
    <li>
      $Sbuffer@:<br />
      $A The common buffer header. It contains the window size and allows the window to be used as a $St_bunny_buffer@.
    </li>
    <li>
      $Sname@:<br />
      $A The name sent to $Sbunny_start@ or $Sbunny_start_style@ when the window was opened.
    </li>
    <li>
      $Sstyle@:<br />
      $A The $St_bunny_window_style@ used when the window was created.
    </li>
    <li>
      $Sposition@:<br />
      $A The last known desktop position of the window.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_start@</li>
    <li>$Sbunny_start_style@</li>
    <li>$Sbunny_stop@</li>
    <li>$Sbunny_display@</li>
  </ul>
</div>
