<?php /* Generated by generate_doc.php from include/lapin/window.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_window_style@<br />
{<br />
&nbsp;&nbsp;$CNO_BORDER@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;0,<br />
&nbsp;&nbsp;$CTITLEBAR@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;1,<br />
&nbsp;&nbsp;$CRESIZE_BUTTON@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;2,<br />
&nbsp;&nbsp;$CCLOSE_BUTTON@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;4,<br />
&nbsp;&nbsp;$CFULLSCREEN@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;8,<br />
&nbsp;&nbsp;$CDEFAULT_WIN_STYLE@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;$CTITLEBAR@&nbsp;|&nbsp;$CRESIZE_BUTTON@&nbsp;|&nbsp;$CCLOSE_BUTTON@,<br />
&nbsp;&nbsp;$CANTIALIASING@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;16<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_window_style@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Describes how a window should be created by $Sbunny_start_style@.<br />
  <br />
  $St_bunny_window_style@ is a bitmask enumeration. Most values can be combined with the binary $COR@ operator to ask the system for several window decorations at the same time.<br />
  <br />
  $CFULLSCREEN@ is intended to be used as a fullscreen creation mode. $CANTIALIASING@ is a LibLapin flag that can be added to another style to request antialiasing when the render window is created.<br />
</div>
<hr />

<div class="symbols">
  <h3>Symbols</h3>
  <ul>
    <li>
      $CNO_BORDER@:<br />
      $A Creates a window without title bar, border, resize button or close button.
    </li>
    <li>
      $CTITLEBAR@:<br />
      $A Adds a title bar to the window. The title bar usually displays the window name and allows the user to move the window.
    </li>
    <li>
      $CRESIZE_BUTTON@:<br />
      $A Adds the resize or maximize decoration when the window manager supports it.
    </li>
    <li>
      $CCLOSE_BUTTON@:<br />
      $A Adds the close button decoration when the window manager supports it. The system may still provide other ways to close a window.
    </li>
    <li>
      $CFULLSCREEN@:<br />
      $A Creates a fullscreen window.
    </li>
    <li>
      $CDEFAULT_WIN_STYLE@:<br />
      $A The style used by $Sbunny_start@ for a regular window.
    </li>
    <li>
      $CANTIALIASING@:<br />
      $A Requests antialiasing when creating the window.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_start_style@</li>
    <li>$Sbunny_start@</li>
  </ul>
</div>
