<?php /* Generated by generate_doc.php from src/window/start.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tt_bunny_window@ *$Sbunny_start@($Tunsigned@ $Tint@ $Swidth@, $Tunsigned@ $Tint@ $Sheight@, $Tbool@ $Sfullscreen@, $Kconst@ $Tchar@ *$Swinname@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Open a window and return a structure to handle it.<br />
  <br />
  If the window is started in $Sfullscreen@, then not all sizes are available. Use $Sbunny_get_fullscreen_modes@ to retrieve the working $Sfullscreen@ modes for the underlying system.<br />
  <br />
  The returned structure must be freed with $Sbunny_stop@. It is important to call it before exiting, especially in $Sfullscreen@, because it restores the original screen resolution if the window opening changed it.<br />
  <br />
  This function performs a joystick scan. When opening a window, all joysticks will be recognized. After opening the window, connection and disconnection must be handled with events.<br />
  <br />
  By default, the window is filled with $CPINK2@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tunsigned@ $Tint@ $Swidth@:<br />
      $A The $Swidth@ in pixels of the window to open.
    </li>
    <li>
      $Tunsigned@ $Tint@ $Sheight@:<br />
      $A The $Sheight@ in pixels of the window to open.
    </li>
    <li>
      $Tbool@ $Sfullscreen@:<br />
      $A Send $Ctrue@ to open the window in $Sfullscreen@, $Cfalse@ for windowed mode.
    </li>
    <li>
      $Kconst@ $Tchar@ *$Swinname@:<br />
      $A The name of the window. It is displayed in the title bar and stored in the $St_bunny_window@ structure.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A pointer to a valid $St_bunny_window@ structure.
    </li>
    <li>
      On $Bfailure@, $CNULL@ if the window cannot be created.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CBE_UNKNOWN_DISPLAY_DEVICE@:<br />
      <p>
        The display device could not be found or opened.<br />
      </p>
    </li>
    <li>
      $CBE_CANNOT_OPEN_WINDOW@:<br />
      <p>
        The window could not be created.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    This function writes log entries in the $L"graphics"@ and/or $L"window"@ log domains when the window creation fails or when the display mode cannot be applied.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_start_style@</li>
    <li>$Sbunny_stop@</li>
    <li>$Sbunny_get_fullscreen_modes@</li>
    <li>$Sbunny_get_screen_resolution@</li>
  </ul>
</div>
