<?php /* Generated by generate_doc.php from src/window/stop.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_stop@($Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Swindow@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Destroys a $Swindow@ opened by LibLapin.<br />
  <br />
  This function closes the underlying system $Swindow@, releases the $Swindow@ name and destroys the $St_bunny_window@ structure. If the $Swindow@ changed the screen resolution when it was opened, the system is expected to restore the previous mode.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_window@			*$Swindow@:<br />
      $A The $Swindow@ to destroy.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"window"@ label.<br />
  May emit a log in $L"window"@ with pattern $L"%zu"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_start@</li>
    <li>$Sbunny_start_style@</li>
  </ul>
</div>
