<?php /* Generated by generate_doc.php from src/graphics/display.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_display@($Kconst@&nbsp;$Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Swindow@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Refreshes the $Swindow@ content on screen.<br />
  <br />
  Call this function after drawing into a $Swindow@ to make the result appear on screen.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tt_bunny_window@		*$Swindow@:<br />
      $A The $Swindow@ to display and refresh on screen.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"window"@ and $L"graphics"@ labels.<br />
  May emit a log in $L"window,graphics"@ with pattern $L"%p"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_blit@</li>
    <li>$St_bunny_window@</li>
  </ul>
</div>
