<?php /* Generated by generate_doc.php from src/window/get_screen_resolution.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Kconst@&nbsp;$Tt_bunny_size@&nbsp;*$Sbunny_get_screen_resolution@($Tvoid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the current desktop resolution.<br />
  <br />
  Starting a fullscreen window with this size should not force the system to resize the desktop brutally.<br />
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bcase@, success A pointer to a $St_bunny_size@ structure containing the current screen width and height.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"system"@ label.<br />
  May emit a log in $L"system"@ with pattern $L"-&gt; %p(%d, %d)"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_get_fullscreen_modes@</li>
    <li>$Sbunny_start@</li>
    <li>$Sbunny_start_style@</li>
  </ul>
</div>
