<?php /* Generated by generate_doc.php from src/window/get_fullscreen_modes.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Kconst@&nbsp;$Tt_bunny_size@&nbsp;*$Sbunny_get_fullscreen_modes@($Tvoid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the fullscreen modes accepted by the system.<br />
  <br />
  The returned array contains every fullscreen mode reported by the system and is terminated by an item filled with zero.<br />
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bcase@, success A pointer to an array of $St_bunny_size@ structures. The last item is filled with zero.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"system"@ label.<br />
  May emit a log in $L"system"@ with pattern $L"-&gt; %p"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_start@</li>
    <li>$Sbunny_start_style@</li>
    <li>$Sbunny_get_screen_resolution@</li>
  </ul>
</div>
