<?php /* Generated by generate_doc.php from src/window/start.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbunny_start_style@($Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Swidth@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sheight@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_window_style@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sstyle@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Kconst@&nbsp;$Tchar@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sname@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Opens a window with an explicit window $Sstyle@.<br />
  <br />
  This function is the styled version of $Sbunny_start@. Use it when you need to choose the window decorations yourself, open a borderless window, request fullscreen, or add $CANTIALIASING@ to the creation flags.<br />
  <br />
  If $CFULLSCREEN@ is used, the requested size must be supported by the system. Use $Sbunny_get_fullscreen_modes@ to list valid fullscreen modes.<br />
  <br />
  The returned window must be destroyed with $Sbunny_stop@. By default, the window is filled with $CPINK2@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tunsigned@ $Tint@			$Swidth@:<br />
      $A The $Swidth@ in pixels of the window to open.
    </li>
    <li>
      $Tunsigned@ $Tint@			$Sheight@:<br />
      $A The $Sheight@ in pixels of the window to open.
    </li>
    <li>
      $Tt_bunny_window_style@		$Sstyle@:<br />
      $A The $St_bunny_window_style@ flags used to create the window.
    </li>
    <li>
      $Kconst@ $Tchar@			*$Sname@:<br />
      $A The $Sname@ of the window. It is displayed in the title bar and stored in the $St_bunny_window@ structure.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bcase@, failure $CNULL@ if the window cannot be created.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CBE_UNKNOWN_DISPLAY_DEVICE@:<br />
      <p>
        The display device could not be found or opened.<br />
      </p>
    </li>
    <li>
      $CENOMEM@:<br />
      <p>
        The window structure or the underlying render window could not be allocated.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    This function writes log entries in the $L"window"@ log domain when the window is opened or when the creation fails.<br />
  May emit a log in $L"window"@ with pattern $CPATTERN@.<br />
  May emit an error log in $L"window"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_start@</li>
    <li>$Sbunny_stop@</li>
    <li>$Sbunny_get_screen_resolution@</li>
    <li>$Sbunny_get_fullscreen_modes@</li>
    <li>$St_bunny_window_style@</li>
  </ul>
</div>
