<?php /* Generated by generate_doc.php from src/window/set_mouse_visibility.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_set_mouse_visibility@($Kconst@&nbsp;$Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Swindow@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Svisible@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Shows or hides the system mouse cursor over a $Swindow@.<br />
  <br />
  This function controls the visibility of the system cursor when it moves over the given $Swindow@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tt_bunny_window@	*$Swindow@:<br />
      $A The $Swindow@ whose cursor visibility must be changed.
    </li>
    <li>
      $Tbool@			$Svisible@:<br />
      $A Send $Ctrue@ to show the cursor, $Cfalse@ to hide it.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"system"@ and $L"window"@ labels.<br />
  May emit a log in $L"system,window"@ with pattern $L"%p window, %s visible"@.
  </p>
</div>
<hr />

