<?php /* Generated by generate_doc.php from src/window/request_focus.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_request_focus@($Kconst@&nbsp;$Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Swindow@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Asks the $Swindow@ manager to give focus to a $Swindow@.<br />
  <br />
  The system or $Swindow@ manager may refuse the request, especially if focus stealing prevention is enabled.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tt_bunny_window@	*$Swindow@:<br />
      $A The $Swindow@ that requests focus.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"window"@ label.<br />
  May emit a log in $L"window"@ with pattern $L"%p"@.
  </p>
</div>
<hr />

