<?php /* Generated by generate_doc.php from src/window/move_window.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_move_window@($Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Swindow@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_position@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sposition@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Asks the system to move a $Swindow@ on the desktop.<br />
  <br />
  The $Sposition@ is expressed in desktop coordinates. The $Swindow@ manager may adjust or refuse the requested $Sposition@ depending on the platform and user configuration.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_window@		*$Swindow@:<br />
      $A The $Swindow@ to move.
    </li>
    <li>
      $Tt_bunny_position@		$Sposition@:<br />
      $A The requested $Sposition@ for the top-left corner of the $Swindow@.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"window"@ label.<br />
  May emit a log in $L"window"@ with pattern $L"%p window, (%d, %d) position"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_get_window_position@</li>
  </ul>
</div>
