<?php /* Generated by generate_doc.php from include/lapin/window.h; do not edit manually. */ ?>
<div class="resume">
  <h3>Description</h3>
  Opens and manages windows and screen-related services.<br />
  <br />
  The Window module is about opening and managing windows and system-related things that go through windows. It also handles some screen-related features.<br />
  <br />
  <br />
  $BThe window module header is lapin/window.h@<br />
</div>
