#!/usr/bin/bash

DEBUG=""
if [[ " $* " == *" -g "* ]]
then
    DEBUG="-dbg"
fi

g++ -std=gnu++23 "$@" -llapin$DEBUG -lao -lsfml-graphics-s -lsfml-audio-s -lsfml-window-s -lsfml-system-s -lvorbis -lvorbisfile -logg -lvorbisenc -lX11 -lXrandr -lXcursor -lXi -lXext -lFLAC -lstdc++ -lm -ldl -lpthread -lopencv_imgproc -lopencv_objdetect -lopencv_highgui -lopencv_video -lopencv_core -lavcall -lusb -lopencv_videoio -ludev -lfreetype

