<div class="prototype">
  $Tt_bunny_server@ *$Sbunny_new_server_opt@(
  $Tuint16_t@ $Sport@,
  $Tt_bunny_protocol@ $Sprotocol@
  );
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  $A Create a new server. It will contains a listening socket of
  type $Sprotocol@ and listen on $Sport@.<br />
  <br />
  The returned server must be deleted with bunny_delete_server.
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tuint16_t@ $Sport@:<br />
      $A The port on which the server with listen.
    </li>
    <li>
      $Tt_bunny_protocol@ $Sprotocol@:<br />
      $A The nature of the listening socket.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, the function returns the address of a valid
      t_bunny_server.
    </li>
    <li>
      On $Bfailure@, it returns $CNULL@.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Vbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CENOMEM@:<br />
      <p>
        Out of memory.
      </p>
    </li>
    <li>
      Any errno code that can be generated by socket, bind or listen.
    </li>
  </ul>
  <br />
  <p>
    Logs written by this function are tagged with the $L"network"@ label.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>bunny_new_server</li>
    <li>bunny_delete_server</li>
  </ul>
</div>

