<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ts_bunny_clipable@<br />
{<br />
&nbsp;&nbsp;$Tt_bunny_buffer@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbuffer@;<br />
&nbsp;&nbsp;$Tint32_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sclip_x_position@;<br />
&nbsp;&nbsp;$Tint32_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sclip_y_position@;<br />
&nbsp;&nbsp;$Tint32_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sclip_width@;<br />
&nbsp;&nbsp;$Tint32_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sclip_height@;<br />
&nbsp;&nbsp;$Tt_bunny_accurate_position@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sposition@;<br />
&nbsp;&nbsp;$Tt_bunny_accurate_position@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sorigin@;<br />
&nbsp;&nbsp;$Tt_bunny_accurate_position@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sscale@;<br />
&nbsp;&nbsp;$Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Srotation@;<br />
&nbsp;&nbsp;$Tt_bunny_color@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Scolor_mask@;<br />
&nbsp;&nbsp;$Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssmooth@;<br />
&nbsp;&nbsp;$Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Smosaic@;<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_clipable@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Describes a graphic element that can be clipped, positioned, scaled, rotated and color-masked.<br />
  <br />
  This structure inherits from $St_bunny_buffer@ by having it as first field. It can therefore be passed to functions expecting a $St_bunny_buffer@ when appropriate.<br />
  <br />
  The clipping fields select the subpart used as a source. The position, origin, scale and rotation fields describe how the clipable is transformed when it is drawn.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_clipable_copy@</li>
    <li>$Sbunny_set_clipable_attribute@</li>
    <li>$Sbunny_blit@</li>
    <li>$Sbunny_picture@</li>
    <li>$St_bunny_pixelarray@</li>
  </ul>
</div>
