<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  #&nbsp;define&nbsp;$Sbunny_clipable_copy@($Sdest@,&nbsp;$Sori@)&nbsp;do;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Copies the public transformation attributes of a clipable into another one.<br />
  <br />
  The buffer itself and the underlying graphic resource are not copied. Only clipping, position, origin, scale, rotation, color mask and display flags are copied.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Sdest@:<br />
      $A The clipable that receives the copied attributes.
    </li>
    <li>
      $Sori@:<br />
      $A The clipable used as source.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_clipable@</li>
  </ul>
</div>
