<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ts_bunny_pixelarray@<br />
{<br />
&nbsp;&nbsp;$Tt_bunny_clipable@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sclipable@;<br />
&nbsp;&nbsp;$Tvoid@&nbsp;*&nbsp;$Kconst@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Spixels@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tunsigned@&nbsp;$Tchar@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbits_per_pixels@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbitplane@;<br />
&nbsp;&nbsp;$Tunsigned@&nbsp;$Tshort@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Scolor_palette_size@;<br />
&nbsp;&nbsp;$Tt_bunny_color@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Scolor_palette@[256];<br />
&nbsp;&nbsp;$Tuint8_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Scolor_shifts@[4];<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_pixelarray@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Represents a graphic buffer stored in system memory with direct pixel access.<br />
  <br />
  A pixelarray is convenient when pixels must be read or written manually. By default, LibLapin does not draw into pixelarrays unless the matching $Sgl_bunny_my_@* callbacks are provided.<br />
  <br />
  The pixels field starts at the top-left pixel and is stored line after line.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_new_pixelarray@</li>
    <li>$Sbunny_forge_pixelarray@</li>
    <li>$Sbunny_load_pixelarray@</li>
    <li>$Sbunny_delete_clipable@</li>
  </ul>
</div>
