<?php /* Generated by generate_doc.php from src/graphics/load_pixelarray.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tt_bunny_pixelarray@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbunny_load_pixelarray@($Kconst@&nbsp;$Tchar@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sfile@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Loads an image $Sfile@ into a pixelarray.<br />
  <br />
  Supported image formats depend on the $CSFML@ backend and LibLapin loaders. Configuration files can also be used to describe a clipable resource.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tchar@		*$Sfile@:<br />
      $A The path of the image $Sfile@ or clipable configuration $Sfile@ to load.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A loaded $St_bunny_pixelarray@.
    </li>
    <li>
      On $Bfailure@, $CNULL@ on failure.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CENOMEM@:<br />
      <p>
        Out of memory.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Logs are written with the $L"ressource"@ and $L"graphics"@ labels.<br />
  May emit a log in $L"ressource,graphics"@ with pattern $CPATTERN@.<br />
  May emit an error log in $L"ressource,graphics"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_new_pixelarray@</li>
    <li>$Sbunny_read_pixelarray_id@</li>
    <li>$Sbunny_save_pixelarray@</li>
  </ul>
</div>
