<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Tt_bunny_pixelarray@&nbsp;*(*$Tt_bunny_my_load_pixelarray@)($Kconst@&nbsp;$Tchar@&nbsp;*$Sfile@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Type of a custom image-$Sfile@ loader returning a pixelarray.<br />
  <br />
  This extension point is intended for image formats not handled by the library loader.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      *$Tt_bunny_my_load_pixelarray@)($Kconst@ $Tchar@ *$Sfile@:<br />
      $A The path of the $Sfile@ to load.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A loaded $St_bunny_pixelarray@.
    </li>
    <li>
      On $Bfailure@, $CNULL@ when the custom loader cannot load the $Sfile@.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sgl_bunny_my_load_pixelarray@</li>
    <li>$Sbunny_load_pixelarray@</li>
  </ul>
</div>
