<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Tt_bunny_pixelarray@&nbsp;*(*$Tt_bunny_my_read_pixelarray@)($Kconst@&nbsp;$Tvoid@&nbsp;*$Sbuf@,&nbsp;$Tsize_t@&nbsp;$Slength@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Type of a custom in-memory image reader returning a pixelarray.<br />
  <br />
  This extension point is intended for encoded image data already present in memory.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      *$Tt_bunny_my_read_pixelarray@)($Kconst@ $Tvoid@ *$Sbuf@:<br />
      $A The memory buffer containing the encoded picture.
    </li>
    <li>
      $Tsize_t@ $Slength@:<br />
      $A The size of $Sbuf@ in bytes.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A loaded $St_bunny_pixelarray@.
    </li>
    <li>
      On $Bfailure@, $CNULL@ when the custom reader cannot read the buffer.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sgl_bunny_my_read_pixelarray@</li>
    <li>$Sbunny_read_pixelarray_id@</li>
  </ul>
</div>
