<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Kextern@&nbsp;$Tt_bunny_my_load_pixelarray@&nbsp;$Sgl_bunny_my_load_pixelarray@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Custom pixelarray loader hook.<br />
  <br />
  Assign a $St_bunny_my_load_pixelarray@ function here to extend picture loading with additional file formats.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_my_load_pixelarray@</li>
    <li>$Sbunny_load_pixelarray@</li>
  </ul>
</div>
