<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Kextern@&nbsp;$Tt_bunny_my_read_pixelarray@&nbsp;$Sgl_bunny_my_read_pixelarray@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Custom in-memory pixelarray reader hook.<br />
  <br />
  Assign a $St_bunny_my_read_pixelarray@ function here to extend image decoding from memory.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_my_read_pixelarray@</li>
    <li>$Sbunny_read_pixelarray_id@</li>
  </ul>
</div>
