<?php /* Generated by generate_doc.php from src/graphics/save_pixelarray.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_save_pixelarray@($Kconst@&nbsp;$Tt_bunny_pixelarray@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbuf@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Kconst@&nbsp;$Tchar@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sfile@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Saves a pixelarray into an image $Sfile@.<br />
  <br />
  The exact output capabilities, including alpha preservation, depend on the selected $Sfile@ format and backend support.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tt_bunny_pixelarray@	*$Sbuf@:<br />
      $A The pixelarray to save.
    </li>
    <li>
      $Kconst@ $Tchar@		*$Sfile@:<br />
      $A The destination $Sfile@ path.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, $Ctrue@ if the $Sfile@ was written.
    </li>
    <li>
      On $Bfailure@, $Cfalse@ if saving fails.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $Cerrno@:<br />
      <p>
        The backend or filesystem error reported by the save operation.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Logs are written with the $L"ressource"@ and $L"graphics"@ labels.<br />
  May emit a log in $L"ressource,graphics"@ with pattern $CPATTERN@.<br />
  May emit an error log in $L"ressource,graphics"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_load_pixelarray@</li>
    <li>$Sbunny_read_pixelarray_id@</li>
  </ul>
</div>
