<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Tt_bunny_clipable@&nbsp;$Tt_bunny_picture@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Represents a graphic resource stored on the graphic backend.<br />
  <br />
  Pictures are faster than pixelarrays for blits and complex drawing operations. They do not provide fast direct pixel access.<br />
  <br />
  All $St_bunny_clipable@ attributes are meaningful on pictures.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_clipable@</li>
    <li>$Sbunny_new_picture@</li>
    <li>$Sbunny_load_picture@</li>
    <li>$Sbunny_delete_clipable@</li>
  </ul>
</div>
