<?php /* Generated by generate_doc.php from src/graphics/new_picture.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tt_bunny_picture@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbunny_new_picture@($Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Swid@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Shei@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Creates a new picture stored by the graphic backend.<br />
  <br />
  The returned object must be destroyed with $Sbunny_delete_clipable@. If normal-map support is enabled, a matching normal render target is also prepared.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tunsigned@ $Tint@			$Swid@:<br />
      $A The width in pixels.
    </li>
    <li>
      $Tunsigned@ $Tint@			$Shei@:<br />
      $A The height in pixels.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A valid $St_bunny_picture@.
    </li>
    <li>
      On $Bfailure@, $CNULL@ if allocation or backend creation fails.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CENOMEM@:<br />
      <p>
        Out of memory.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Logs are written with the $L"ressource"@ and $L"graphics"@ labels.<br />
  May emit a log in $L"ressource,graphics"@ with pattern $CPATTERN@.<br />
  May emit an error log in $L"ressource,graphics"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_picture@</li>
    <li>$Sbunny_load_picture@</li>
    <li>$Sbunny_delete_clipable@</li>
  </ul>
</div>
