<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  #define&nbsp;$Sbunny_read_picture@($Sbuffer@,&nbsp;$Slen@)&nbsp;\&nbsp;$Sbunny_read_picture_id@($Sbuffer@,&nbsp;$Slen@,&nbsp;$CNULL@)&nbsp;/*!&nbsp;**&nbsp;**&nbsp;*/&nbsp;/**&nbsp;*&nbsp;@doc-symbol&nbsp;$Tt_bunny_clipable_type@&nbsp;*&nbsp;@doc-module&nbsp;graphics&nbsp;*&nbsp;@doc-kind&nbsp;type&nbsp;*&nbsp;@doc-order&nbsp;165&nbsp;*&nbsp;@doc-since&nbsp;12&nbsp;*&nbsp;@doc-until&nbsp;latest&nbsp;*&nbsp;@doc-level&nbsp;advanced&nbsp;*&nbsp;*&nbsp;@doc-lang&nbsp;en&nbsp;*&nbsp;@brief&nbsp;Identifies&nbsp;the&nbsp;concrete&nbsp;kind&nbsp;of&nbsp;clipable&nbsp;configured&nbsp;by&nbsp;$Sbunny_set_clipable_attribute@.&nbsp;*&nbsp;@description&nbsp;The&nbsp;value&nbsp;tells&nbsp;the&nbsp;configuration&nbsp;loader&nbsp;whether&nbsp;it&nbsp;must&nbsp;create&nbsp;or&nbsp;configure&nbsp;a&nbsp;pixelarray,&nbsp;picture,&nbsp;sprite,&nbsp;font,&nbsp;tilemap,&nbsp;parallax&nbsp;or&nbsp;cinematic&nbsp;object.&nbsp;*&nbsp;@see&nbsp;$Sbunny_set_clipable_attribute@&nbsp;*&nbsp;*&nbsp;@doc-lang&nbsp;fr&nbsp;*&nbsp;@brief&nbsp;Identifie&nbsp;le&nbsp;type&nbsp;concret&nbsp;de&nbsp;clipable&nbsp;configuré&nbsp;par&nbsp;$Sbunny_set_clipable_attribute@.&nbsp;*&nbsp;@description&nbsp;La&nbsp;valeur&nbsp;indique&nbsp;au&nbsp;chargeur&nbsp;de&nbsp;configuration&nbsp;s’il&nbsp;doit&nbsp;créer&nbsp;ou&nbsp;configurer&nbsp;un&nbsp;pixelarray,&nbsp;une&nbsp;picture,&nbsp;un&nbsp;sprite,&nbsp;une&nbsp;police,&nbsp;une&nbsp;tilemap,&nbsp;un&nbsp;parallax&nbsp;ou&nbsp;une&nbsp;cinématique.&nbsp;*&nbsp;@see&nbsp;$Sbunny_set_clipable_attribute@&nbsp;*/&nbsp;$Ktypedef@&nbsp;$Kenum@&nbsp;$Tt_bunny_clipable_type@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Reads an image file already loaded in memory and returns it as a picture.<br />
  <br />
  This is a convenience macro calling $Sbunny_read_picture_id@ with a $SNULL@ resource identifier.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Sbuffer@:<br />
      $A The memory $Sbuffer@ containing the complete encoded picture file.
    </li>
    <li>
      $Slen@) \ $Sbunny_read_picture_id@($Sbuffer@:<br />
      $A The memory $Sbuffer@ containing the complete encoded picture file.
    </li>
    <li>
      $Slen@:<br />
      $A The size of $Sbuffer@ in bytes.
    </li>
    <li>
      $CNULL@:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A newly allocated $St_bunny_picture@.
    </li>
    <li>
      On $Bfailure@, $SNULL@ on failure.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_read_picture_id@</li>
    <li>$Sbunny_load_picture@</li>
    <li>$Sbunny_new_picture@</li>
  </ul>
</div>
