<?php /* Generated by generate_doc.php from src/graphics/delete_clipable.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_bunny_delete_clipable($Tt_bunny_clipable@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sclip@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Destroys a clipable graphic object.<br />
  <br />
  Use the public $Sbunny_delete_clipable@ macro rather than calling _bunny_delete_clipable directly. It accepts pictures, pixelarrays, sprites, fonts, tilemaps, parallax and cinematic objects.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_clipable@ *$Sclip@:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CEINVAL@:<br />
      <p>
        The object kind is not recognized.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Logs are written with the $L"graphics"@ label.<br />
  May emit a log in $L"graphics"@ with pattern $L"%p"@.<br />
  May emit an error log in $L"graphics"@ with pattern $L"%p"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_clipable@</li>
    <li>$Sbunny_new_picture@</li>
    <li>$Sbunny_new_pixelarray@</li>
  </ul>
</div>
