<?php /* Generated by generate_doc.php from src/graphics/blit.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_blit@($Tt_bunny_buffer@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbuf@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Kconst@&nbsp;$Tt_bunny_clipable@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sclp@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Kconst@&nbsp;$Tt_bunny_position@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Spos@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Draws a clipable source on a target buffer.<br />
  <br />
  The target can be a window, a picture or, when the proper user callback is installed, a pixelarray. If position is $CNULL@, the source position field is used.<br />
  <br />
  When the source is a pixelarray, full transformations and alpha require $Sbunny_enable_full_blit@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_buffer@			*$Sbuf@:<br />
      $A The target buffer.
    </li>
    <li>
      $Kconst@ $Tt_bunny_clipable@		*$Sclp@:<br />
      $A The source clipable.
    </li>
    <li>
      $Kconst@ $Tt_bunny_position@		*$Spos@:<br />
      $A The destination position, or $CNULL@ to use $Sclp@-&gt;position.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CEINVAL@:<br />
      <p>
        The target or source kind is not supported.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Logs are written with the $L"graphics"@ label.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_blit_shader@</li>
    <li>$Sbunny_enable_full_blit@</li>
    <li>$St_bunny_my_blit@</li>
    <li>$Sgl_bunny_my_blit@</li>
  </ul>
</div>
