<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Kextern@&nbsp;$Tt_bunny_my_blit@&nbsp;$Sgl_bunny_my_blit@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Pixelarray blitter hook used by $Sbunny_blit@.<br />
  <br />
  The default value is $CNULL@. When it is $CNULL@, $Sbunny_blit@ cannot draw into a $St_bunny_pixelarray@.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_my_blit@</li>
    <li>$Sbunny_blit@</li>
  </ul>
</div>
