<?php /* Generated by generate_doc.php from src/graphics/draw.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_draw@($Kconst@&nbsp;$Tt_bunny_picture@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Spicture@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Flushes pending drawing operations on a $Spicture@-like object.<br />
  <br />
  Call this on render-target pictures before using them as sources for further blits.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tt_bunny_picture@		*$Spicture@:<br />
      $A The $Spicture@ or compatible object to update.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    Logs are written with the $L"graphics"@ label.<br />
  May emit a log in $L"graphics"@ with pattern $L"%p"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_blit@</li>
    <li>$Sbunny_set_geometry@</li>
  </ul>
</div>
