<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Kextern@&nbsp;$Tt_bunny_my_set_line@&nbsp;$Sgl_bunny_my_set_line@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Pixelarray line-drawing hook used by $Sbunny_set_line@.<br />
  <br />
  The default value is $CNULL@. Assign a matching callback to enable this operation on $St_bunny_pixelarray@ targets.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_my_set_line@</li>
    <li>$Sbunny_set_line@</li>
  </ul>
</div>
