<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tvoid@(*$Tt_bunny_my_set_polygon@)($Tt_bunny_pixelarray@&nbsp;*$Spix@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Kconst@&nbsp;$Tt_bunny_position@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Spos@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Kconst@&nbsp;$Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Scolor@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Type of a user function that draws a filled triangle into a pixelarray.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      *$Tt_bunny_my_set_polygon@)($Tt_bunny_pixelarray@ *$Spix@:<br />
      $A The destination pixelarray.
    </li>
    <li>
      $Kconst@ $Tt_bunny_position@*$Spos@:<br />
      $A The three triangle points.
    </li>
    <li>
      $Kconst@ $Tunsigned@ $Tint@ *$Scolor@:<br />
      $A The three point colors used for the gradient.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sgl_bunny_my_set_polygon@</li>
    <li>$Sbunny_set_polygon@</li>
  </ul>
</div>
