<?php /* Generated by generate_doc.php from src/graphics/fill.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_fill@($Tt_bunny_buffer@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbuffer@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Scolor@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Applies a $Scolor@ over the clipped area of a $Sbuffer@ using alpha blending.<br />
  <br />
  Unlike $Sbunny_clear@, this operation applies alpha. Drawing into pixelarrays requires $Sgl_bunny_my_fill@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_buffer@			*$Sbuffer@:<br />
      $A The target $Sbuffer@.
    </li>
    <li>
      $Tunsigned@ $Tint@				$Scolor@:<br />
      $A The $Scolor@ to apply.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CEINVAL@:<br />
      <p>
        The target kind is not supported.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Logs are written with the $L"graphics"@ label.<br />
  May emit a log in $L"graphics"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_clear@</li>
    <li>$St_bunny_my_fill@</li>
    <li>$Sgl_bunny_my_fill@</li>
  </ul>
</div>
