<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_geometry@<br />
{<br />
&nbsp;&nbsp;$CBGY_PIXELS@,<br />
&nbsp;&nbsp;$CBGY_LINES@,<br />
&nbsp;&nbsp;$CBGY_LINE_STRIP@,<br />
&nbsp;&nbsp;$CBGY_TRIANGLES@,<br />
&nbsp;&nbsp;$CBGY_TRIANGLE_STRIP@,<br />
&nbsp;&nbsp;$CBGY_TRIANGLE_FAN@,<br />
&nbsp;&nbsp;$CBGY_QUADS@,<br />
&nbsp;&nbsp;$CLAST_GEOMETRY@<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_geometry@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Enumerates primitive modes for $Sbunny_set_geometry@.<br />
  <br />
  Each value changes how the vertices stored in $St_bunny_vertex_array@ are grouped before being drawn.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_set_geometry@</li>
    <li>$St_bunny_vertex_array@</li>
  </ul>
</div>
