<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ts_bunny_vertex_array@<br />
{<br />
&nbsp;&nbsp;$Tsize_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Slength@;<br />
&nbsp;&nbsp;$Tt_bunny_vertex@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Svertex@[__ZERO_LENGTH__];<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_vertex_array@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Stores a variable-length array of vertices.<br />
  <br />
  Reserve enough memory for the header plus the required number of $St_bunny_vertex@ entries before filling length and vertex.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_vertex@</li>
    <li>$Sbunny_set_geometry@</li>
  </ul>
</div>
