<?php /* Generated by generate_doc.php from include/lapin/graphics.h; do not edit manually. */ ?>
<div class="prototype">
  $Kextern@&nbsp;$Tt_bunny_my_geometry@&nbsp;$Sgl_bunny_my_geometry@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Pixelarray geometry hook used by $Sbunny_set_geometry@.<br />
  <br />
  The default value is $CNULL@. Assign a matching callback to enable this operation on $St_bunny_pixelarray@ targets.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_my_geometry@</li>
    <li>$Sbunny_set_geometry@</li>
  </ul>
</div>
