<?php /* Generated by generate_doc.php from src/graphics/enable_full_blit.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_enable_full_blit@($Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Senable@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Enables or disables complete pixelarray source handling in $Sbunny_blit@.<br />
  <br />
  When enabled, blits from pixelarrays support clipping, transformations and alpha handling more completely. The default is disabled.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tbool@			$Senable@:<br />
      $A $Ctrue@ to $Senable@ full blit support, $Cfalse@ to disable it.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_blit@</li>
    <li>$St_bunny_my_blit@</li>
    <li>$Sgl_bunny_my_blit@</li>
  </ul>
</div>
