<?php /* Generated by generate_doc.php from src/graphics/make_clipable_unique.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_make_clipable_unique@($Tt_bunny_clipable@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sclipable@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Ensures that a shared $Sclipable@ owns unique graphic data before modification.<br />
  <br />
  Resources loaded through the resource manager can share the same underlying data. This function duplicates the data when needed, similarly to copy-on-write. Objects created with $Sbunny_new_@* are already unique.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_clipable@	*$Sclipable@:<br />
      $A The $Sclipable@ to make unique.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, $Ctrue@ if the $Sclipable@ is unique or was made unique.
    </li>
    <li>
      On $Bfailure@, $Cfalse@ if duplication fails.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CENOMEM@:<br />
      <p>
        Out of memory while duplicating the resource.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Logs are written with the $L"graphics"@ label.<br />
  May emit a log in $L"graphics"@ with pattern $CPATTERN@.<br />
  May emit an error log in $L"graphics"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_load_picture@</li>
    <li>$Sbunny_load_pixelarray@</li>
  </ul>
</div>
