<?php /* Generated by generate_doc.php from include/lapin/compat.h; do not edit manually. */ ?>
<div class="prototype">
  ;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Compatibility alias for $Sbunny_reset_gl_states@.<br />
  <br />
  This public macro is kept for source compatibility and forwards to $Sbunny_reset_gl_states@.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_reset_gl_states@</li>
  </ul>
</div>
