<?php /* Generated by generate_doc.php from include/lapin/events.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_response@<br />
{<br />
&nbsp;&nbsp;$CEXIT_ON_ERROR@,<br />
&nbsp;&nbsp;$CEXIT_ON_CROSS@,<br />
&nbsp;&nbsp;$CEXIT_ON_SUCCESS@,<br />
&nbsp;&nbsp;$CSWITCH_CONTEXT@,<br />
&nbsp;&nbsp;$CSWITCH_WINDOW@,<br />
&nbsp;&nbsp;$CGO_ON@,<br />
&nbsp;&nbsp;$CLEAVE_EVENT@,<br />
&nbsp;&nbsp;$CNOTHING_HAPPENED@<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_response@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Enumerates the actions a callback can request from the event loop.<br />
  <br />
  Every event callback returns a $St_bunny_response@. $CGO_ON@ keeps the loop running; most other values stop the current loop and are returned to the caller.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_loop@</li>
    <li>$Sbunny_loop_mw@</li>
    <li>$St_bunny_context@</li>
  </ul>
</div>
