<?php /* Generated by generate_doc.php from include/lapin/events.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_event_state@<br />
{<br />
&nbsp;&nbsp;$CGO_DOWN@,<br />
&nbsp;&nbsp;$CGO_UP@,<br />
&nbsp;&nbsp;$CLOST_FOCUS@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;$CGO_DOWN@,<br />
&nbsp;&nbsp;$CGOT_FOCUS@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;$CGO_UP@,<br />
&nbsp;&nbsp;$CCONNECTED@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;$CGO_DOWN@,<br />
&nbsp;&nbsp;$CDISCONNECTED@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;$CGO_UP@,<br />
&nbsp;&nbsp;$CENTERING@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;$CGO_DOWN@,<br />
&nbsp;&nbsp;$CLEAVING@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;$CGO_UP@<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_event_state@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Describes whether an event starts or ends.<br />
  <br />
  $CGO_DOWN@ and $CGO_UP@ are the generic names. The other symbols are aliases used to make focus, joystick connection and context transitions easier to read.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_key@</li>
    <li>$St_bunny_click@</li>
    <li>$St_bunny_joy_connect@</li>
  </ul>
</div>
