<?php /* Generated by generate_doc.php from include/lapin/enum.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_keysym@<br />
{<br />
&nbsp;&nbsp;$CBKS_UNKNOWN@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;-1,<br />
&nbsp;&nbsp;$CBKS_A@,<br />
&nbsp;&nbsp;$CBKS_B@,<br />
&nbsp;&nbsp;$CBKS_C@,<br />
&nbsp;&nbsp;$CBKS_D@,<br />
&nbsp;&nbsp;$CBKS_E@,<br />
&nbsp;&nbsp;$CBKS_F@,<br />
&nbsp;&nbsp;$CBKS_G@,<br />
&nbsp;&nbsp;$CBKS_H@,<br />
&nbsp;&nbsp;$CBKS_I@,<br />
&nbsp;&nbsp;$CBKS_J@,<br />
&nbsp;&nbsp;$CBKS_K@,<br />
&nbsp;&nbsp;$CBKS_L@,<br />
&nbsp;&nbsp;$CBKS_M@,<br />
&nbsp;&nbsp;$CBKS_N@,<br />
&nbsp;&nbsp;$CBKS_O@,<br />
&nbsp;&nbsp;$CBKS_P@,<br />
&nbsp;&nbsp;$CBKS_Q@,<br />
&nbsp;&nbsp;$CBKS_R@,<br />
&nbsp;&nbsp;$CBKS_S@,<br />
&nbsp;&nbsp;$CBKS_T@,<br />
&nbsp;&nbsp;$CBKS_U@,<br />
&nbsp;&nbsp;$CBKS_V@,<br />
&nbsp;&nbsp;$CBKS_W@,<br />
&nbsp;&nbsp;$CBKS_X@,<br />
&nbsp;&nbsp;$CBKS_Y@,<br />
&nbsp;&nbsp;$CBKS_Z@,<br />
&nbsp;&nbsp;$CBKS_0@,<br />
&nbsp;&nbsp;$CBKS_1@,<br />
&nbsp;&nbsp;$CBKS_2@,<br />
&nbsp;&nbsp;$CBKS_3@,<br />
&nbsp;&nbsp;$CBKS_4@,<br />
&nbsp;&nbsp;$CBKS_5@,<br />
&nbsp;&nbsp;$CBKS_6@,<br />
&nbsp;&nbsp;$CBKS_7@,<br />
&nbsp;&nbsp;$CBKS_8@,<br />
&nbsp;&nbsp;$CBKS_9@,<br />
&nbsp;&nbsp;$CBKS_ESCAPE@,<br />
&nbsp;&nbsp;$CBKS_LCONTROL@,<br />
&nbsp;&nbsp;$CBKS_LSHIFT@,<br />
&nbsp;&nbsp;$CBKS_LALT@,<br />
&nbsp;&nbsp;$CBKS_LSYSTEM@,<br />
&nbsp;&nbsp;$CBKS_RCONTROL@,<br />
&nbsp;&nbsp;$CBKS_RSHIFT@,<br />
&nbsp;&nbsp;$CBKS_RALT@,<br />
&nbsp;&nbsp;$CBKS_RSYSTEM@,<br />
&nbsp;&nbsp;$CBKS_MENU@,<br />
&nbsp;&nbsp;$CBKS_LBRACKET@,<br />
&nbsp;&nbsp;$CBKS_RBRACKET@,<br />
&nbsp;&nbsp;$CBKS_SEMICOLON@,<br />
&nbsp;&nbsp;$CBKS_COMMA@,<br />
&nbsp;&nbsp;$CBKS_PERIOD@,<br />
&nbsp;&nbsp;$CBKS_QUOTE@,<br />
&nbsp;&nbsp;$CBKS_SLASH@,<br />
&nbsp;&nbsp;$CBKS_BACKSLASH@,<br />
&nbsp;&nbsp;$CBKS_TILDE@,<br />
&nbsp;&nbsp;$CBKS_EQUAL@,<br />
&nbsp;&nbsp;$CBKS_DASH@,<br />
&nbsp;&nbsp;$CBKS_SPACE@,<br />
&nbsp;&nbsp;$CBKS_RETURN@,<br />
&nbsp;&nbsp;$CBKS_BACKSPACE@,<br />
&nbsp;&nbsp;$CBKS_TAB@,<br />
&nbsp;&nbsp;$CBKS_PAGEUP@,<br />
&nbsp;&nbsp;$CBKS_PAGEDOWN@,<br />
&nbsp;&nbsp;$CBKS_END@,<br />
&nbsp;&nbsp;$CBKS_HOME@,<br />
&nbsp;&nbsp;$CBKS_INSERT@,<br />
&nbsp;&nbsp;$CBKS_DELETE@,<br />
&nbsp;&nbsp;$CBKS_ADD@,<br />
&nbsp;&nbsp;$CBKS_SUBTRACT@,<br />
&nbsp;&nbsp;$CBKS_MULTIPLY@,<br />
&nbsp;&nbsp;$CBKS_DIVIDE@,<br />
&nbsp;&nbsp;$CBKS_LEFT@,<br />
&nbsp;&nbsp;$CBKS_RIGHT@,<br />
&nbsp;&nbsp;$CBKS_UP@,<br />
&nbsp;&nbsp;$CBKS_DOWN@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD0@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD1@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD2@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD3@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD4@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD5@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD6@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD7@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD8@,<br />
&nbsp;&nbsp;$CBKS_NUMPAD9@,<br />
&nbsp;&nbsp;$CBKS_F1@,<br />
&nbsp;&nbsp;$CBKS_F2@,<br />
&nbsp;&nbsp;$CBKS_F3@,<br />
&nbsp;&nbsp;$CBKS_F4@,<br />
&nbsp;&nbsp;$CBKS_F5@,<br />
&nbsp;&nbsp;$CBKS_F6@,<br />
&nbsp;&nbsp;$CBKS_F7@,<br />
&nbsp;&nbsp;$CBKS_F8@,<br />
&nbsp;&nbsp;$CBKS_F9@,<br />
&nbsp;&nbsp;$CBKS_F10@,<br />
&nbsp;&nbsp;$CBKS_F11@,<br />
&nbsp;&nbsp;$CBKS_F12@,<br />
&nbsp;&nbsp;$CBKS_F13@,<br />
&nbsp;&nbsp;$CBKS_F14@,<br />
&nbsp;&nbsp;$CBKS_F15@,<br />
&nbsp;&nbsp;$CBKS_PAUSE@,<br />
&nbsp;&nbsp;$CBKS_LAST_KEY@<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_keysym@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Enumerates keyboard keys handled by LibLapin.<br />
  <br />
  These symbols are used by key press and key release callbacks. Use $Sbunny_get_keyname@ to turn a symbol into a printable name.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_key@</li>
    <li>$Sbunny_set_key_response@</li>
    <li>$Sbunny_get_keyname@</li>
    <li>$Sgl_bunny_keysym@</li>
  </ul>
</div>
