<?php /* Generated by generate_doc.php from src/events/get_keyboard.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Kconst@&nbsp;$Tbool@&nbsp;*$Sbunny_get_keyboard@($Tvoid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the current keyboard state array.<br />
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A pointer to the keyboard state array, where $Ctrue@ means down and $Cfalse@ means up.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_key@</li>
    <li>$Sbunny_set_key_response@</li>
  </ul>
</div>
