<?php /* Generated by generate_doc.php from include/lapin/enum.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_mouse_button@<br />
{<br />
&nbsp;&nbsp;$CBMB_LEFT@,<br />
&nbsp;&nbsp;$CBMB_RIGHT@,<br />
&nbsp;&nbsp;$CBMB_MIDDLE@,<br />
&nbsp;&nbsp;$CBMB_EXTRABUTTON0@,<br />
&nbsp;&nbsp;$CBMB_EXTRABUTTON1@,<br />
&nbsp;&nbsp;$CLAST_BUNNY_MOUSEBUTTON@<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_mouse_button@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Enumerates mouse buttons handled by LibLapin.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_click@</li>
    <li>$Sbunny_get_mouse_button@</li>
  </ul>
</div>
