<?php /* Generated by generate_doc.php from src/events/get_mouse_position.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Kconst@&nbsp;$Tt_bunny_position@&nbsp;*$Sbunny_get_mouse_position@($Tvoid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the last known mouse position.<br />
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A pointer to the current mouse position structure.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_move@</li>
    <li>$Sbunny_set_move_response@</li>
  </ul>
</div>
