<?php /* Generated by generate_doc.php from src/events/get_joy_info.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Kconst@&nbsp;$Tt_bunny_joystick@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbunny_get_joy_info@($Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns information about a joystick slot.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tint@				$Sid@:<br />
      $A The joystick slot identifier.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A pointer to the requested $St_bunny_joystick@ information structure.
    </li>
    <li>
      On $Bfailure@, $CNULL@ if $Sid@ is outside the supported joystick range.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_joystick@</li>
    <li>$Sbunny_update_joysticks@</li>
  </ul>
</div>
