<?php /* Generated by generate_doc.php from src/events/get_joy_axis.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Kconst@&nbsp;$Tfloat@&nbsp;(*$Sbunny_get_joy_axis@($Tvoid@))[$CLAST_BUNNY_AXIS@];
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the current joystick axis state array.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      *$Sbunny_get_joy_axis@($Tvoid@):<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A pointer to the joystick axis state array.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_joy_axis@</li>
    <li>$Sbunny_set_joy_axis_response@</li>
    <li>$Sbunny_set_joy_axis_minimum_offset@</li>
  </ul>
</div>
