<?php /* Generated by generate_doc.php from src/events/get_window.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Kconst@&nbsp;$Tt_bunny_window@&nbsp;*$Sbunny_get_window@($Tvoid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the window currently producing an event.<br />
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, The window that is currently being processed.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_loop@</li>
    <li>$Sbunny_loop_mw@</li>
  </ul>
</div>
