<?php /* Generated by generate_doc.php from src/events/set_display_function.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_set_display_function@($Tt_bunny_display@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sdisplay@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Registers the $Sdisplay@ callback.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_display@	$Sdisplay@:<br />
      $A The callback to call when the loop decides that $Sdisplay@ should be refreshed.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_display@</li>
    <li>$Sbunny_loop@</li>
    <li>$Sbunny_loop_mw@</li>
  </ul>
</div>
