<?php /* Generated by generate_doc.php from include/lapin/events.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_response@(*$Tt_bunny_loop@)($Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sdat@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Callback type for fixed-frequency main loop events.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      *$Tt_bunny_loop@)($Tvoid@ *$Sdat@:<br />
      $A The data pointer sent to $Sbunny_loop@ or $Sbunny_loop_mw@.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, $CGO_ON@ to keep the loop running, or another $St_bunny_response@ to stop or change it.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_set_loop_main_function@</li>
    <li>$Sbunny_loop@</li>
    <li>$Sbunny_loop_mw@</li>
  </ul>
</div>
