<?php /* Generated by generate_doc.php from src/events/loop_mw.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tt_bunny_response@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_loop_mw@($Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**$Swin@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tsize_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Snwin@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sfreq@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sdata@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Runs the event loop for several windows.<br />
  <br />
  This function behaves like $Sbunny_loop@ but receives an array of windows. Window event handling is per-window, while loop and display callbacks remain shared.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_window@			**$Swin@:<br />
      $A The array of windows that produce events.
    </li>
    <li>
      $Tsize_t@				$Snwin@:<br />
      $A The number of entries in $Swin@.
    </li>
    <li>
      $Tunsigned@ $Tint@			$Sfreq@:<br />
      $A The requested number of main-loop callback calls per second.
    </li>
    <li>
      $Tvoid@				*$Sdata@:<br />
      $A The $Sdata@ pointer sent to every registered callback.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, The $St_bunny_response@ value that stopped the loop.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    This function writes log entries in the $L"event"@ log domain when entering the loop and dispatching callbacks.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"Entering)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"enter_context)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"event %p)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"close window %p)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"gain_focus %p)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"lost_focus %p)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"reisze %p)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"keydown)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"keyup)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"text)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"joyconnect)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"joydisconnect)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"joydown)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"joyup)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"joymove)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"mousedown)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"mouseup)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"mousewheel)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"mousemove)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"loop)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"display)"@.<br />
  May emit a log in $L"event"@ with pattern $CPATTERN@ $L"leave_context)"@.<br />
  May emit a log in $L"event"@ with pattern $L"%p window, %zu nbr_window, %u frequency, %p parameter -&gt; %d (Exiting)"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_loop@</li>
    <li>$Sbunny_get_window@</li>
    <li>$Sbunny_set_close_response@</li>
  </ul>
</div>
