<?php /* Generated by generate_doc.php from src/events/get_frequency.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tint@&nbsp;$Sbunny_get_frequency@($Tvoid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the current main-loop frequency.<br />
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, The number of loop callback calls requested per second under normal performance conditions.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_get_delay@</li>
    <li>$Sbunny_loop@</li>
    <li>$Sbunny_loop_mw@</li>
  </ul>
</div>
