<?php /* Generated by generate_doc.php from src/events/set_async_computation.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_set_async_computation_response@($Tt_bunny_async_computation_response@&nbsp;$Sfunc@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Registers the callback called when an asynchronous computation completes.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_async_computation_response@ $Sfunc@:<br />
      $A The callback to call.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_async_computation_response@</li>
    <li>$Sbunny_async_computation@</li>
  </ul>
</div>
