<?php /* Generated by generate_doc.php from include/lapin/events.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ts_bunny_context@<br />
{<br />
&nbsp;&nbsp;$Tt_bunny_key@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Skey@;<br />
&nbsp;&nbsp;$Tt_bunny_type@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Stype@;<br />
&nbsp;&nbsp;$Tt_bunny_click@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sclick@;<br />
&nbsp;&nbsp;$Tt_bunny_move@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Smove@;<br />
&nbsp;&nbsp;$Tt_bunny_wheel@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Swheel@;<br />
&nbsp;&nbsp;$Kunion@&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_joy_connect@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;connect;<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_joy_connect@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;joy_connect;<br />
&nbsp;&nbsp;};<br />
&nbsp;&nbsp;$Kunion@&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_joy_button@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;button;<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_joy_button@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;joy_button;<br />
&nbsp;&nbsp;};<br />
&nbsp;&nbsp;$Kunion@&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_joy_axis@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis;<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_joy_axis@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;joy_axis;<br />
&nbsp;&nbsp;};<br />
&nbsp;&nbsp;$Tt_bunny_get_focus@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sget_focus@;<br />
&nbsp;&nbsp;$Tt_bunny_lost_focus@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Slost_focus@;<br />
&nbsp;&nbsp;$Tt_bunny_resize@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sresize@;<br />
&nbsp;&nbsp;$Tt_bunny_loop@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sloop@;<br />
&nbsp;&nbsp;$Tt_bunny_display@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sdisplay@;<br />
&nbsp;&nbsp;$Tt_bunny_close@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sclose@;<br />
&nbsp;&nbsp;$Kunion@&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_message_response@&nbsp;&nbsp;&nbsp;&nbsp;net_message;<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_message_response@&nbsp;&nbsp;&nbsp;&nbsp;netmessage&nbsp;_BDEPREC();<br />
&nbsp;&nbsp;};<br />
&nbsp;&nbsp;$Kunion@&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_connect_response@&nbsp;&nbsp;&nbsp;&nbsp;net_connect;<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_connect_response@&nbsp;&nbsp;&nbsp;&nbsp;netconnect&nbsp;_BDEPREC();<br />
&nbsp;&nbsp;};<br />
&nbsp;&nbsp;$Tt_bunny_loop@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sentering_context@;<br />
&nbsp;&nbsp;$Tt_bunny_leaving_context@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sleaving_context@;<br />
&nbsp;&nbsp;$Kunion@&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_async_computation_response@&nbsp;async_computation;<br />
&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_async_computation_response@&nbsp;async_computation_response&nbsp;_BDEPREC();<br />
&nbsp;&nbsp;};<br />
&nbsp;&nbsp;$Tt_bunny_event_response@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sevent@;<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_context@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Groups all event callbacks into a single context structure.<br />
  <br />
  Each $CNULL@ function pointer disables the corresponding callback. This structure can be installed with $Sbunny_set_context@ and copied back with $Sbunny_get_context@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      );
  };
  $Kunion@ {
    $Tt_bunny_connect_response@	net_connect;
    $Tt_bunny_connect_response@	netconnect _BDEPREC();
  };
  $Tt_bunny_loop@			entering_context;
  $Tt_bunny_leaving_context@	leaving_context;
  $Kunion@ {
    $Tt_bunny_async_computation_response@ async_computation;
    $Tt_bunny_async_computation_response@ async_computation_response _BDEPREC(:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_set_context@</li>
    <li>$Sbunny_get_context@</li>
    <li>$Sbunny_declare_context@</li>
  </ul>
</div>
