<?php /* Generated by generate_doc.php from include/lapin/events.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;$Ts_bunny_anonymous_context@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Deprecated untyped variant of $St_bunny_context@.<br />
  <br />
  It stores callbacks as void pointers so user callbacks can use a specific data type without casts, but this breaks type safety. Prefer $Sbunny_declare_context@ with $St_bunny_context@.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_context@</li>
    <li>$Sbunny_declare_context@</li>
  </ul>
</div>
