<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_music_track@<br />
{<br />
&nbsp;&nbsp;$CBST_ALL@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;-1,<br />
&nbsp;&nbsp;$CBST_TRACK_01@,<br />
&nbsp;&nbsp;$CBST_TRACK_02@,<br />
&nbsp;&nbsp;$CBST_TRACK_03@,<br />
&nbsp;&nbsp;$CBST_TRACK_04@,<br />
&nbsp;&nbsp;$CBST_LAST_TRACK@<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_music_track@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Enumerates independent music tracks handled by a sound manager.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_sound_manager_play_music@</li>
    <li>$Sbunny_sound_manager_stop_music@</li>
  </ul>
</div>
