<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kenum@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Te_bunny_sound_type@<br />
{<br />
&nbsp;&nbsp;$CBST_GENERAL@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;-1,<br />
&nbsp;&nbsp;$CBST_MUSIC@,<br />
&nbsp;&nbsp;$CBST_EFFECT@,<br />
&nbsp;&nbsp;$CBST_VOICE@,<br />
&nbsp;&nbsp;$CBST_LAST_SOUND_TYPE@<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_sound_type@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Enumerates categories used to apply common volume and pitch settings.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_sound_manager_add@</li>
    <li>$Sbunny_sound_manager_volume@</li>
    <li>$Sbunny_sound_manager_pitch@</li>
  </ul>
</div>
