<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ts_bunny_sound_manager@<br />
{<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tt_bunny_sound@&nbsp;*&nbsp;$Kconst@&nbsp;&nbsp;&nbsp;$Scurrent_music@[$CBST_LAST_TRACK@];<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sgeneral_volume@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Svolumes@[$CBST_LAST_SOUND_TYPE@];<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sgeneral_pitch@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Spitches@[$CBST_LAST_SOUND_TYPE@];<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_sound_manager@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Centralized sound controller for volumes, pitches and music tracks.<br />
  <br />
  It groups sounds into categories so a game can expose global, music, effect and voice controls.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sgl_bunny_sound_manager@</li>
    <li>$Sbunny_sound_manager_add@</li>
  </ul>
</div>
