<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  $Kextern@&nbsp;$Tt_bunny_sound_manager@&nbsp;$Sgl_bunny_sound_manager@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Global sound manager provided by LibLapin.<br />
  <br />
  It avoids carrying a manager pointer everywhere. You can still create your own manager if needed.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_sound_manager@</li>
    <li>$Sbunny_sound_manager_add@</li>
  </ul>
</div>
