<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  #&nbsp;if&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;defined($S__STDC_VERSION__@)&nbsp;&amp;&amp;&nbsp;$S__STDC_VERSION__@&nbsp;==&nbsp;201112L&nbsp;/*!&nbsp;**&nbsp;Add&nbsp;a&nbsp;sound&nbsp;inside&nbsp;the&nbsp;sound&nbsp;manager&nbsp;associated&nbsp;to&nbsp;a&nbsp;category.&nbsp;**&nbsp;Its&nbsp;volume&nbsp;and&nbsp;pitch&nbsp;will&nbsp;be&nbsp;modified&nbsp;accordingly&nbsp;to&nbsp;general&nbsp;and&nbsp;category&nbsp;**&nbsp;volume&nbsp;and&nbsp;pitch,&nbsp;associated&nbsp;to&nbsp;its&nbsp;proper&nbsp;one.&nbsp;**&nbsp;\param&nbsp;$Ssm@&nbsp;The&nbsp;sound&nbsp;manager.&nbsp;**&nbsp;\param&nbsp;$Ssnd@&nbsp;The&nbsp;sound&nbsp;to&nbsp;insert&nbsp;**&nbsp;\param&nbsp;typ&nbsp;The&nbsp;category&nbsp;in&nbsp;which&nbsp;the&nbsp;sound&nbsp;will&nbsp;be&nbsp;added,&nbsp;it&nbsp;cannot&nbsp;be&nbsp;general.&nbsp;**&nbsp;\$Kreturn@&nbsp;True&nbsp;if&nbsp;the&nbsp;sound&nbsp;was&nbsp;inserted&nbsp;or&nbsp;was&nbsp;already&nbsp;inserted&nbsp;in&nbsp;the&nbsp;**&nbsp;matching&nbsp;category.&nbsp;False&nbsp;on&nbsp;error.&nbsp;*/&nbsp;#&nbsp;define&nbsp;$Sbunny_sound_manager_add@(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;typ)&nbsp;\&nbsp;_bunny_sound_manager_add&nbsp;\&nbsp;(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Generic(($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_music@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_sound_sprite@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_effect@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_sound@*:&nbsp;($Ssnd@)&nbsp;\&nbsp;),<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;typ)&nbsp;#&nbsp;else&nbsp;#&nbsp;define&nbsp;$Sbunny_sound_manager_add@(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;typ)&nbsp;\&nbsp;_bunny_sound_manager_add(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;typ)&nbsp;#&nbsp;endif&nbsp;/*!&nbsp;**&nbsp;Remove&nbsp;a&nbsp;sound&nbsp;from&nbsp;the&nbsp;sound&nbsp;manager.&nbsp;**&nbsp;\param&nbsp;$Ssm@&nbsp;The&nbsp;sound&nbsp;manager&nbsp;**&nbsp;\param&nbsp;$Ssnd@&nbsp;The&nbsp;sound&nbsp;to&nbsp;remove&nbsp;*/&nbsp;$Tvoid@&nbsp;_bunny_sound_manager_remove($Tt_bunny_sound_manager@&nbsp;*$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_sound@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Ssnd@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Adds a sound to a manager and associates it with a category.<br />
  <br />
  Managed sounds should use $Sbunny_managed_sound_volume@ and $Sbunny_managed_sound_pitch@ instead of direct sound setters.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $S__STDC_VERSION__@) &amp;&amp; $S__STDC_VERSION__@ == 201112L /*! ** Add a sound inside the sound manager associated to a category. ** Its volume and pitch will be modified accordingly to general and category ** volume and pitch, associated to its proper one. ** \param $Ssm@ The sound manager. ** \param $Ssnd@ The sound to insert ** \param typ The category in which the sound will be added, it cannot be general. ** \$Kreturn@ True if the sound was inserted or was already inserted in the ** matching category. False on error. */ # define $Sbunny_sound_manager_add@($Ssm@:<br />
      $A 
    </li>
    <li>
      $Ssnd@:<br />
      $A Sound, music, sound sprite or effect to add.
    </li>
    <li>
      typ) \ _bunny_sound_manager_add \ ($Ssm@:<br />
      $A Sound manager that will contain the association.
    </li>
    <li>
      _Generic(($Ssnd@), \ $Tt_bunny_music@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_sound_sprite@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_effect@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_sound@*: ($Ssnd@) \ ):<br />
      $A 
    </li>
    <li>
      typ) # else # define $Sbunny_sound_manager_add@($Ssm@:<br />
      $A Sound manager that will contain the association.
    </li>
    <li>
      $Ssnd@:<br />
      $A Sound, music, sound sprite or effect to add.
    </li>
    <li>
      typ) \ _bunny_sound_manager_add($Ssm@:<br />
      $A Sound manager that will contain the association.
    </li>
    <li>
      $Ssnd@:<br />
      $A Sound, music, sound sprite or effect to add.
    </li>
    <li>
      typ) # endif /*! ** Remove a sound from the sound manager. ** \param $Ssm@ The sound manager ** \param $Ssnd@ The sound to remove */ $Tvoid@ _bunny_sound_manager_remove($Tt_bunny_sound_manager@ *$Ssm@:<br />
      $A Sound manager that will contain the association.
    </li>
    <li>
      $Tt_bunny_sound@ *$Ssnd@:<br />
      $A Sound, music, sound sprite or effect to add.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, $Ctrue@ if the sound was inserted or was already in the same category.
    </li>
    <li>
      On $Bfailure@, $Cfalse@ if the category is invalid or the sound is already in another category.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_sound_manager_remove@</li>
    <li>$Sbunny_managed_sound_volume@</li>
    <li>$Sbunny_managed_sound_pitch@</li>
  </ul>
</div>
