<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  #&nbsp;if&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;defined($S__STDC_VERSION__@)&nbsp;&amp;&amp;&nbsp;$S__STDC_VERSION__@&nbsp;==&nbsp;201112L&nbsp;/*!&nbsp;**&nbsp;Remove&nbsp;a&nbsp;sound&nbsp;from&nbsp;the&nbsp;sound&nbsp;manager.&nbsp;**&nbsp;\param&nbsp;$Ssm@&nbsp;The&nbsp;sound&nbsp;manager&nbsp;**&nbsp;\param&nbsp;$Ssnd@&nbsp;The&nbsp;sound&nbsp;to&nbsp;remove&nbsp;*/&nbsp;#&nbsp;define&nbsp;$Sbunny_sound_manager_remove@(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@)&nbsp;\&nbsp;_bunny_sound_manager_remove&nbsp;\&nbsp;(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Generic(($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_music@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_sound_sprite@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_effect@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_sound@*:&nbsp;($Ssnd@)&nbsp;\&nbsp;))&nbsp;#&nbsp;else&nbsp;#&nbsp;define&nbsp;$Sbunny_sound_manager_remove@(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@)&nbsp;\&nbsp;_bunny_sound_manager_remove(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@)&nbsp;#&nbsp;endif&nbsp;/*!&nbsp;**&nbsp;Play&nbsp;a&nbsp;music&nbsp;on&nbsp;the&nbsp;sent&nbsp;track.&nbsp;Stop&nbsp;the&nbsp;previous&nbsp;music&nbsp;if&nbsp;any&nbsp;on&nbsp;the&nbsp;track.&nbsp;**&nbsp;If&nbsp;the&nbsp;music&nbsp;that&nbsp;was&nbsp;playing&nbsp;is&nbsp;the&nbsp;same&nbsp;as&nbsp;the&nbsp;sent&nbsp;one,&nbsp;does&nbsp;nothing.&nbsp;**&nbsp;If&nbsp;$CALL@&nbsp;is&nbsp;sent&nbsp;as&nbsp;track,&nbsp;all&nbsp;tracks&nbsp;are&nbsp;stopped&nbsp;and&nbsp;the&nbsp;music&nbsp;is&nbsp;played&nbsp;on&nbsp;**&nbsp;track&nbsp;1.&nbsp;**&nbsp;\param&nbsp;$Ssm@&nbsp;The&nbsp;sound&nbsp;manager&nbsp;**&nbsp;\param&nbsp;$Ssnd@&nbsp;The&nbsp;music&nbsp;to&nbsp;play&nbsp;**&nbsp;\param&nbsp;$Sn@&nbsp;The&nbsp;track&nbsp;on&nbsp;which&nbsp;to&nbsp;play&nbsp;the&nbsp;music&nbsp;**&nbsp;\$Kreturn@&nbsp;True&nbsp;if&nbsp;the&nbsp;music&nbsp;is&nbsp;played&nbsp;or&nbsp;was&nbsp;already&nbsp;playing,&nbsp;else&nbsp;false.&nbsp;*/&nbsp;$Tbool@&nbsp;$Sbunny_sound_manager_play_music@($Tt_bunny_sound_manager@&nbsp;*$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_music@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_music_track@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sn@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Removes a sound from a sound manager.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $S__STDC_VERSION__@) &amp;&amp; $S__STDC_VERSION__@ == 201112L /*! ** Remove a sound from the sound manager. ** \param $Ssm@ The sound manager ** \param $Ssnd@ The sound to remove */ # define $Sbunny_sound_manager_remove@($Ssm@:<br />
      $A 
    </li>
    <li>
      $Ssnd@) \ _bunny_sound_manager_remove \ ($Ssm@:<br />
      $A Sound manager from which the sound is removed.
    </li>
    <li>
      _Generic(($Ssnd@), \ $Tt_bunny_music@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_sound_sprite@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_effect@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_sound@*: ($Ssnd@) \ )) # else # define $Sbunny_sound_manager_remove@($Ssm@:<br />
      $A Sound manager from which the sound is removed.
    </li>
    <li>
      $Ssnd@) \ _bunny_sound_manager_remove($Ssm@:<br />
      $A Sound manager from which the sound is removed.
    </li>
    <li>
      $Ssnd@) # endif /*! ** Play a music on the sent track. Stop the previous music if any on the track. ** If the music that was playing is the same as the sent one, does nothing. ** If $CALL@ is sent as track, all tracks are stopped and the music is played on ** track 1. ** \param $Ssm@ The sound manager ** \param $Ssnd@ The music to play ** \param $Sn@ The track on which to play the music ** \$Kreturn@ True if the music is played or was already playing, else false. */ $Tbool@ $Sbunny_sound_manager_play_music@($Tt_bunny_sound_manager@ *$Ssm@:<br />
      $A Sound manager from which the sound is removed.
    </li>
    <li>
      $Tt_bunny_music@ *$Ssnd@:<br />
      $A Sound, music, sound sprite or effect to remove.
    </li>
    <li>
      $Tt_bunny_music_track@ $Sn@:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_sound_manager_add@</li>
    <li>$Sbunny_delete_sound@</li>
  </ul>
</div>
