<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  #&nbsp;if&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;defined($S__STDC_VERSION__@)&nbsp;&amp;&amp;&nbsp;$S__STDC_VERSION__@&nbsp;==&nbsp;201112L&nbsp;/*!&nbsp;**&nbsp;Set&nbsp;the&nbsp;proper&nbsp;volume&nbsp;of&nbsp;the&nbsp;sent&nbsp;sound.&nbsp;**&nbsp;\param&nbsp;$Ssm@&nbsp;The&nbsp;sound&nbsp;manager&nbsp;**&nbsp;\param&nbsp;$Ssnd@&nbsp;The&nbsp;sound&nbsp;**&nbsp;\param&nbsp;vol&nbsp;The&nbsp;proper&nbsp;volume&nbsp;of&nbsp;the&nbsp;sent&nbsp;sound&nbsp;**&nbsp;\$Kreturn@&nbsp;True&nbsp;if&nbsp;the&nbsp;sound&nbsp;was&nbsp;found&nbsp;and&nbsp;set,&nbsp;else&nbsp;false.&nbsp;*/&nbsp;#&nbsp;define&nbsp;$Sbunny_managed_sound_volume@(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vol)&nbsp;\&nbsp;_bunny_managed_sound_volume&nbsp;\&nbsp;(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Generic(($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_music@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_effect@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_sound_sprite@*:&nbsp;($Tt_bunny_sound@*)($Ssnd@),&nbsp;\&nbsp;$Tt_bunny_sound@*:&nbsp;($Ssnd@)&nbsp;\&nbsp;),<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vol)&nbsp;#&nbsp;else&nbsp;#&nbsp;define&nbsp;$Sbunny_managed_sound_volume@(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vol)&nbsp;\&nbsp;_bunny_managed_sound_volume(&nbsp;$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vol)&nbsp;#&nbsp;endif&nbsp;/*!&nbsp;**&nbsp;Set&nbsp;the&nbsp;proper&nbsp;pitch&nbsp;of&nbsp;the&nbsp;sent&nbsp;sound.&nbsp;**&nbsp;\param&nbsp;$Ssm@&nbsp;The&nbsp;sound&nbsp;manager&nbsp;**&nbsp;\param&nbsp;$Ssnd@&nbsp;The&nbsp;sound&nbsp;**&nbsp;\param&nbsp;$Spit@&nbsp;The&nbsp;proper&nbsp;pitch&nbsp;of&nbsp;the&nbsp;sent&nbsp;sound&nbsp;**&nbsp;\$Kreturn@&nbsp;True&nbsp;if&nbsp;the&nbsp;sound&nbsp;was&nbsp;found&nbsp;and&nbsp;set,&nbsp;else&nbsp;false.&nbsp;*/&nbsp;$Tbool@&nbsp;_bunny_managed_sound_pitch($Tt_bunny_sound_manager@&nbsp;*$Ssm@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_sound@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Ssnd@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Spit@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Sets the proper volume of a managed sound.<br />
  <br />
  The effective volume combines this value, the global manager volume and the category volume.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $S__STDC_VERSION__@) &amp;&amp; $S__STDC_VERSION__@ == 201112L /*! ** Set the proper volume of the sent sound. ** \param $Ssm@ The sound manager ** \param $Ssnd@ The sound ** \param vol The proper volume of the sent sound ** \$Kreturn@ True if the sound was found and set, else false. */ # define $Sbunny_managed_sound_volume@($Ssm@:<br />
      $A 
    </li>
    <li>
      $Ssnd@:<br />
      $A Managed sound to update.
    </li>
    <li>
      vol) \ _bunny_managed_sound_volume \ ($Ssm@:<br />
      $A Sound manager containing the sound.
    </li>
    <li>
      _Generic(($Ssnd@), \ $Tt_bunny_music@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_effect@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_sound_sprite@*: ($Tt_bunny_sound@*)($Ssnd@), \ $Tt_bunny_sound@*: ($Ssnd@) \ ):<br />
      $A 
    </li>
    <li>
      vol) # else # define $Sbunny_managed_sound_volume@($Ssm@:<br />
      $A Sound manager containing the sound.
    </li>
    <li>
      $Ssnd@:<br />
      $A Managed sound to update.
    </li>
    <li>
      vol) \ _bunny_managed_sound_volume($Ssm@:<br />
      $A Sound manager containing the sound.
    </li>
    <li>
      $Ssnd@:<br />
      $A Managed sound to update.
    </li>
    <li>
      vol) # endif /*! ** Set the proper pitch of the sent sound. ** \param $Ssm@ The sound manager ** \param $Ssnd@ The sound ** \param $Spit@ The proper pitch of the sent sound ** \$Kreturn@ True if the sound was found and set, else false. */ $Tbool@ _bunny_managed_sound_pitch($Tt_bunny_sound_manager@ *$Ssm@:<br />
      $A Sound manager containing the sound.
    </li>
    <li>
      $Tt_bunny_sound@ *$Ssnd@:<br />
      $A Managed sound to update.
    </li>
    <li>
      $Tdouble@ $Spit@:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, $Ctrue@ if the sound was found and updated.
    </li>
    <li>
      On $Bfailure@, $Cfalse@ if the sound is not managed by $Ssm@.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_managed_sound_pitch@</li>
    <li>$Sbunny_sound_manager_volume@</li>
  </ul>
</div>
