<?php /* Generated by generate_doc.php from include/lapin/sound_manager.h; do not edit manually. */ ?>
<div class="prototype">
  ;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Sets the proper pitch of a managed sound.<br />
  <br />
  The effective pitch combines this value, the global manager pitch and the category pitch.<br />
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, $Ctrue@ if the sound was found and updated.
    </li>
    <li>
      On $Bfailure@, $Cfalse@ if the sound is not managed by sm.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_managed_sound_volume@</li>
    <li>$Sbunny_sound_manager_pitch@</li>
  </ul>
</div>
