/*
** Jason Brillante "Damdoshi"
** Hanged Bunny Studio 2014-2017
**
** Bibliotheque Lapin
*/

/*!
** \file hash.h
** Hash function. As bunny_security, they are not
** made to be safe in term of crack or hack.
*/

#ifndef				__LAPIN_HASH_H__
# define			__LAPIN_HASH_H__

/**
 * @doc
 * @doc-symbol t_bunny_hash_algorithm
 * @doc-kind enum
 * @doc-module hash
 * @doc-order 100
 * @doc-since 11
 * @doc-until latest
 * @doc-level beginner
 *
 * @doc-lang en
 * @brief Lists the weak hash algorithms supported by LibLapin.
 * @description These algorithms are intended for checksums, identifiers or small digests. They are not cryptographic hashes and must not be used as a security primitive.
 * @value BH_MULTIPLIER Multiplicative hash that works well enough with short ASCII strings.
 * @value BH_FNV FNV-style multiplicative hash.
 * @value BH_FNV_A FNV-1a-style multiplicative hash.
 * @value BH_DJB2 DJB2 hash, often efficient in terms of collisions for small textual data.
 * @value BH_SDBM SDBM hash.
 * @value BH_LOSELOSE Very small checksum-like hash.
 * @value BH_CUSTOM First value reserved for user-defined hash algorithms. Any value greater than or equal to it makes bunny_hash call gl_bunny_my_hash.
 * @see t_bunny_hash, bunny_hash, bunny_wide_hash, gl_bunny_my_hash
 *
 * @doc-lang fr
 * @brief Liste les algorithmes de hachage faibles pris en charge par la LibLapin.
 * @description Ces algorithmes sont destinés aux sommes de contrôle, aux identifiants ou aux petits condensats. Ce ne sont pas des hachages cryptographiques et ils ne doivent pas être utilisés comme mécanisme de sécurité.
 * @value BH_MULTIPLIER Hachage multiplicatif qui fonctionne convenablement avec les petites chaînes ASCII.
 * @value BH_FNV Hachage multiplicatif de style FNV.
 * @value BH_FNV_A Hachage multiplicatif de style FNV-1a.
 * @value BH_DJB2 Hachage DJB2, souvent efficace en termes de collisions pour de petites données textuelles.
 * @value BH_SDBM Hachage SDBM.
 * @value BH_LOSELOSE Très petite somme de contrôle.
 * @value BH_CUSTOM Première valeur réservée aux algorithmes de hachage définis par l'utilisateur. Toute valeur supérieure ou égale provoque l'appel de gl_bunny_my_hash par bunny_hash.
 * @see t_bunny_hash, bunny_hash, bunny_wide_hash, gl_bunny_my_hash
 */
typedef enum			e_bunny_hash_algorithm
  {
    BH_MULTIPLIER,
    BH_FNV,
    BH_FNV_A,
    BH_DJB2,
    BH_SDBM,
    BH_LOSELOSE,		// CHECKSUM
    BH_CUSTOM
  }				t_bunny_hash_algorithm;

/**
 * @doc
 * @doc-symbol t_bunny_hash
 * @doc-kind type
 * @doc-module hash
 * @doc-order 110
 * @doc-since 11
 * @doc-until latest
 * @doc-level beginner
 *
 * @doc-lang en
 * @brief Represents the 64-bit digest returned by bunny_hash.
 * @description This type is the storage type of the short hash produced by the hash module. It is not an algorithm selector; use t_bunny_hash_algorithm for that.
 * @see t_bunny_hash_algorithm, bunny_hash, bunny_wide_hash
 *
 * @doc-lang fr
 * @brief Représente le condensat 64 bits renvoyé par bunny_hash.
 * @description Ce type est le type de stockage du hachage court produit par le module hash. Ce n'est pas un sélecteur d'algorithme ; utilisez t_bunny_hash_algorithm pour cela.
 * @see t_bunny_hash_algorithm, bunny_hash, bunny_wide_hash
 */
typedef uint64_t		t_bunny_hash;

t_bunny_hash			bunny_hash(t_bunny_hash_algorithm	hash,
					   const void			*ptr,
					   size_t			len);

/**
 * @doc
 * @doc-symbol t_bunny_my_hash
 * @doc-kind type
 * @doc-module hash
 * @doc-order 140
 * @doc-since 11
 * @doc-until latest
 * @doc-level advanced
 *
 * @doc-lang en
 * @brief Defines the callback type used for custom hash algorithms.
 * @description bunny_hash calls gl_bunny_my_hash when the requested algorithm is BH_CUSTOM or any greater value. The callback can use the algorithm value to dispatch several custom hashes.
 * @param hash The custom algorithm identifier sent to bunny_hash. It is greater than or equal to BH_CUSTOM.
 * @param ptr The data to hash.
 * @param len The length of ptr in bytes.
 * @return-success The digest generated by the custom algorithm.
 * @see t_bunny_hash_algorithm, gl_bunny_my_hash, bunny_hash
 *
 * @doc-lang fr
 * @brief Définit le type de callback utilisé pour les algorithmes de hachage personnalisés.
 * @description bunny_hash appelle gl_bunny_my_hash lorsque l'algorithme demandé vaut BH_CUSTOM ou une valeur supérieure. Le callback peut utiliser la valeur de l'algorithme pour dispatcher plusieurs hachages personnalisés.
 * @param hash L'identifiant d'algorithme personnalisé envoyé à bunny_hash. Il est supérieur ou égal à BH_CUSTOM.
 * @param ptr Les données à hacher.
 * @param len La longueur de ptr en octets.
 * @return-success Le condensat généré par l'algorithme personnalisé.
 * @see t_bunny_hash_algorithm, gl_bunny_my_hash, bunny_hash
 */
typedef uint64_t		(*t_bunny_my_hash)(t_bunny_hash_algorithm hash,
						   const void		*ptr,
						   size_t		len);

/**
 * @doc
 * @doc-symbol gl_bunny_my_hash
 * @doc-kind variable
 * @doc-module hash
 * @doc-order 160
 * @doc-since 11
 * @doc-until latest
 * @doc-level advanced
 *
 * @doc-lang en
 * @brief Stores the callback used by bunny_hash for custom hash algorithms.
 * @description Set this function pointer before calling bunny_hash with BH_CUSTOM or any greater value. If it is NULL when such an algorithm is used, the call is invalid.
 * @see t_bunny_my_hash, t_bunny_hash_algorithm, bunny_hash
 *
 * @doc-lang fr
 * @brief Stocke le callback utilisé par bunny_hash pour les algorithmes de hachage personnalisés.
 * @description Affectez ce pointeur de fonction avant d'appeler bunny_hash avec BH_CUSTOM ou une valeur supérieure. S'il vaut NULL lorsqu'un tel algorithme est utilisé, l'appel est invalide.
 * @see t_bunny_my_hash, t_bunny_hash_algorithm, bunny_hash
 */
extern t_bunny_my_hash		gl_bunny_my_hash;

void				bunny_wide_hash(t_bunny_hash_algorithm	hash,
						const void		*to_hash,
						size_t			to_hash_len,
						void			*storage,
						size_t			storage_len);

#endif	/*			__LAPIN_HASH_H__	*/
