<?php /* Generated by generate_doc.php from include/lapin/sound.h; do not edit manually. */ ?>
<div class="prototype">
  $Ktypedef@&nbsp;$Kstruct@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ts_bunny_effect@<br />
{<br />
&nbsp;&nbsp;$Tt_bunny_sound@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssound@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tsize_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssample_per_second@;<br />
&nbsp;&nbsp;$Kconst@&nbsp;$Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sduration@;<br />
&nbsp;&nbsp;$Tint16_t@&nbsp;*&nbsp;$Kconst@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Ssample@;<br />
}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tt_bunny_effect@;
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Represents a sound effect loaded in memory.<br />
  <br />
  Its sample buffer can be edited manually, then submitted with $Sbunny_compute_effect@ before playback.<br />
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_sound@</li>
    <li>$Sbunny_new_effect@</li>
    <li>$Sbunny_load_effect@</li>
    <li>$Sbunny_compute_effect@</li>
    <li>$Sbunny_delete_sound@</li>
  </ul>
</div>
