<?php /* Generated by generate_doc.php from src/sound/load_effect.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tt_bunny_effect@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbunny_load_effect@($Kconst@&nbsp;$Tchar@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sfile@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Opens a sound effect $Sfile@ or a sound effect configuration $Sfile@.<br />
  <br />
  A sound effect is loaded in memory. Several loads of the same $Sfile@ may share low-level resources.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tchar@			*$Sfile@:<br />
      $A Sound $Sfile@ or configuration $Sfile@ to open. Supported sound formats are wav and ogg.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, A valid $St_bunny_effect@ pointer.
    </li>
    <li>
      On $Bfailure@, $CNULL@ if the effect cannot be loaded.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CENOMEM@:<br />
      <p>
        Out of memory.<br />
      </p>
    </li>
    <li>
      $CEINVAL@:<br />
      <p>
        Invalid $Sfile@ format.<br />
      </p>
    </li>
    <li>
      $CENOENT@:<br />
      <p>
        The $Sfile@ was not found.<br />
      </p>
    </li>
    <li>
      $CBE_SYNTAX_ERROR@:<br />
      <p>
        The configuration $Sfile@ contains a syntax error.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    May log in the $L"ressource"@, $L"configuration"@, $L"syntax"@ and $L"sound"@ domains.<br />
  May emit a log in $L"ressource,sound"@ with pattern $CPATTERN@.<br />
  May emit an error log in $L"ressource,sound"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_new_effect@</li>
    <li>$Sbunny_compute_effect@</li>
    <li>$Sbunny_make_effect_unique@</li>
    <li>$Sbunny_delete_sound@</li>
  </ul>
</div>
