<?php /* Generated by generate_doc.php from src/sound/play.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_sound_play@($Tt_bunny_sound@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Ssound@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Plays a $Ssound@.<br />
  <br />
  Current $Ssound@ attributes are applied before playback. If you edited $St_bunny_effect@.sample, call $Sbunny_compute_effect@ first.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_sound@			*$Ssound@:<br />
      $A Sound to play.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    May log in the $L"ressource"@ and $L"sound"@ domains.<br />
  May emit a log in $L"ressource,sound"@ with pattern $L"%p"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_sound_pause@</li>
    <li>$Sbunny_sound_stop@</li>
    <li>$Sbunny_compute_effect@</li>
  </ul>
</div>
