<?php /* Generated by generate_doc.php from include/lapin/compat.h; do not edit manually. */ ?>
<div class="prototype">
  #define&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_music_get_cursor@(music)&nbsp;\&nbsp;$Sbunny_sound_get_cursor@(&amp;(music)-&gt;sound)&nbsp;/*!&nbsp;**&nbsp;Get&nbsp;a&nbsp;free&nbsp;element&nbsp;inside&nbsp;the&nbsp;pool.&nbsp;**&nbsp;\param&nbsp;$Spol@&nbsp;The&nbsp;pool&nbsp;to&nbsp;browse.&nbsp;**&nbsp;\param&nbsp;$Sid@&nbsp;A&nbsp;pointer&nbsp;to&nbsp;store&nbsp;the&nbsp;$Sid@&nbsp;of&nbsp;the&nbsp;element&nbsp;in&nbsp;the&nbsp;storage&nbsp;array.&nbsp;May&nbsp;be&nbsp;$CNULL@.&nbsp;**&nbsp;\$Kreturn@&nbsp;$CNULL@&nbsp;if&nbsp;there&nbsp;is&nbsp;no&nbsp;free&nbsp;element&nbsp;inside&nbsp;the&nbsp;pool,&nbsp;or&nbsp;a&nbsp;pointer&nbsp;to&nbsp;a&nbsp;free&nbsp;element&nbsp;**&nbsp;*/&nbsp;$Tvoid@&nbsp;*$Sbunny_pool_getv@($Tt_bunny_pool@&nbsp;*$Spol@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tsize_t@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sid@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Compatibility macro returning the cursor position of a music.<br />
  <br />
  It forwards to $Sbunny_sound_get_cursor@ on the embedded $St_bunny_sound@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      music) \ $Sbunny_sound_get_cursor@(&amp;(music)-&gt;sound) /*! ** Get a free element inside the pool. ** \param $Spol@ The pool to browse. ** \param $Sid@ A pointer to store the $Sid@ of the element in the storage array. May be $CNULL@. ** \$Kreturn@ $CNULL@ if there is no free element inside the pool, or a pointer to a free element ** */ $Tvoid@ *$Sbunny_pool_getv@($Tt_bunny_pool@ *$Spol@:<br />
      $A 
    </li>
    <li>
      $Tsize_t@ *$Sid@:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, Current cursor position in seconds.
    </li>
  </ul>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_sound_get_cursor@</li>
    <li>$St_bunny_music@</li>
  </ul>
</div>
