<?php /* Generated by generate_doc.php from src/sound/get_duration.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tdouble@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_sound_get_duration@($Kconst@&nbsp;$Tt_bunny_sound@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Ssnd@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Returns the duration of a sound.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Kconst@ $Tt_bunny_sound@	*$Ssnd@:<br />
      $A Sound to query.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, Duration in seconds.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    May log in the $L"sound"@ domain.<br />
  May emit a log in $L"sound"@ with pattern $L"%p -&gt; %f"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_sound_get_cursor@</li>
  </ul>
</div>
