<?php /* Generated by generate_doc.php from src/sound/delete_sound.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tvoid@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_bunny_delete_sound($Tt_bunny_sound@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Ssound@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Deletes a music, $Ssound@ effect, $Ssound@ sprite or recorder.<br />
  <br />
  The public $CC11@ macro accepts derived $Ssound@ types and calls _bunny_delete_sound.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_sound@ *$Ssound@:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <br />
  <p>
    May log in the $L"ressource"@ and $L"sound"@ domains.<br />
  May emit a log in $L"ressource,sound"@ with pattern $L"%p"@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$St_bunny_sound@</li>
    <li>$Sbunny_load_music@</li>
    <li>$Sbunny_load_effect@</li>
    <li>$Sbunny_new_effect@</li>
  </ul>
</div>
