<?php /* Generated by generate_doc.php from src/sound/make_effect_unique.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sbunny_make_effect_unique@($Tt_bunny_effect@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$S_eff@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Detaches an effect from shared low-level resources.<br />
  <br />
  Call this before editing samples when several effects may share the same loaded file.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tt_bunny_effect@ *$S_eff@:<br />
      $A 
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bsuccess@, $Ctrue@ if the effect is now unique, including when it already was.
    </li>
    <li>
      On $Bfailure@, $Cfalse@ if duplication fails.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CENOMEM@:<br />
      <p>
        Out of memory.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    May log in the $L"sound"@ domain.<br />
  May emit a log in $L"sound"@ with pattern $CPATTERN@.<br />
  May emit an error log in $L"sound"@ with pattern $CPATTERN@.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_load_effect@</li>
    <li>$Sbunny_compute_effect@</li>
  </ul>
</div>
