#!/bin/sh
sleep 0.05
clear
/bin/echo -n ""
/bin/echo -en "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo -n ""
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo -n ""
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo -n ""
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
/bin/echo -n ""
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..O..O..                             "
/bin/echo "                __   ...\/...   __                        "
/bin/echo "               /  \   ......   /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo "                 \__\        /__/                         "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                __    ......    __                        "
/bin/echo -e "               /  \      \033[0;31m|\033[00m     /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
/bin/echo "                \  |          |  /                        "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -e "                __       \033[0;31m|\033[00m       __                        "
/bin/echo -e "               /  \      \033[0;31m|\033[00m      /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo "                /  \__________/  \                        "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -e "                         \033[0;31m|\033[00m                                 "
/bin/echo -e "                __       \033[0;31m|\033[00m       __                        "
/bin/echo -e "               /  \      \033[0;31m|\033[00m      /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
/bin/echo "                 ________________                         "
/bin/echo -n ""
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -e "                         \033[0;31m|\033[00m                                 "
/bin/echo "                                                          "
/bin/echo "                __              __                        "
/bin/echo -e "               /  \      \033[0;31m|\033[00m      /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo "                  ______________                          "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                __              __                        "
/bin/echo "               /  \            /  \                       "
/bin/echo "               \   \__________/   /                       "
/bin/echo "                \  ____________  /                        "
/bin/echo -n ""
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo -e "                         \033[0;31m|\033[00m                                 "
/bin/echo "                                                          "
/bin/echo "                __              __                        "
/bin/echo -e "               /  \      \033[0;31m|\033[00m      /  \                       "
/bin/echo "               \   \__________/   /                       "
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                __              __                        "
/bin/echo -e "               /  \      \033[0;31m|\033[00m      /  \                       "
/bin/echo -n ""
sleep 0.05
clear
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                __              __                        "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -en "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo -n ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       o                                  "
/bin/echo "                                                          "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
/bin/echo "                           |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       o                                  "
/bin/echo "                                                          "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
/bin/echo "                           |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       o                                  "
/bin/echo "                                                          "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
/bin/echo "                           |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       o                                  "
/bin/echo "                                                          "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o   |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                       o                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
/bin/echo "                           |                              "
/bin/echo "                           |                              "
/bin/echo "                       o   o                              "
/bin/echo -ne ""
sleep 0.05
clear
/bin/echo -ne "\033[00m"
/bin/echo "                    LIB LAPIN                             "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                        ||                                "
/bin/echo "                    __  ||  __                            "
/bin/echo "                   /  \ || /  \                           "
/bin/echo "                  / /\ \||/ /\ \                          "
/bin/echo "                  \/  ......  \/                          "
/bin/echo "                     ..X..X..                             "
/bin/echo "                     ...\/...                             "
/bin/echo "                      ......                              "
/bin/echo -ne "\033[0;31m"
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                                                          "
/bin/echo "                       |                                  "
/bin/echo "                       |                                  "
/bin/echo "                                                          "
/bin/echo -ne "\033[00m"
sleep 0.05
clear
