<?php /* Generated by generate_doc.php from src/window/start.cpp; do not edit manually. */ ?>
<div class="prototype">
  $Tt_bunny_window@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sbunny_start@($Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Swidth@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tunsigned@&nbsp;$Tint@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sheight@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Tbool@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Sfullscreen@,<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$Kconst@&nbsp;$Tchar@&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*$Sname@);
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  Ouvre une fenêtre et renvoie une structure permettant de la manipuler.<br />
  <br />
  Si la fenêtre est ouverte en plein écran, toutes les tailles ne sont pas disponibles. Utilisez $Sbunny_get_fullscreen_modes@ pour récupérer les modes plein écran utilisables sur le système sous-jacent.<br />
  <br />
  La structure renvoyée doit être libérée avec $Sbunny_stop@. Il est important de l$L'appeler avant de quitter, en particulier en plein écran, car cela restaure la résolution d'@écran originale si l$L'ouverture de la fenêtre l'@a changée.<br />
  <br />
  Cette fonction effectue un scan des joysticks. Lors de l$L'ouverture d'@une fenêtre, tous les joysticks sont reconnus. Après l'ouverture, les connexions et déconnexions doivent être gérées avec les événements.<br />
  <br />
  Par défaut, la fenêtre est remplie avec $CPINK2@.<br />
</div>
<hr />

<div class="parameters">
  <h3>Parameters</h3>
  <ul>
    <li>
      $Tunsigned@ $Tint@			$Swidth@:<br />
      $A La largeur en pixels de la fenêtre à ouvrir.
    </li>
    <li>
      $Tunsigned@ $Tint@			$Sheight@:<br />
      $A La hauteur en pixels de la fenêtre à ouvrir.
    </li>
    <li>
      $Tbool@				$Sfullscreen@:<br />
      $A Envoyez $Ctrue@ pour ouvrir la fenêtre en plein écran, $Cfalse@ pour le mode fenêtré.
    </li>
    <li>
      $Kconst@ $Tchar@				*$Sname@:<br />
      $A Le nom de la fenêtre. Il est affiché dans la barre de titre et stocké dans la structure $St_bunny_window@.
    </li>
  </ul>
</div>
<hr />

<div class="return">
  <h3>Return value</h3>
  <ul>
    <li>
      On $Bcase@, failure $CNULL@ si la fenêtre ne peut pas être créée.
    </li>
  </ul>
</div>
<hr />

<div class="error_and_log">
  <h3>Error values and logs</h3>
  <p>
    On error, $Sbunny_errno@ is set to:
  </p>
  <br />
  <ul>
    <li>
      $CBE_UNKNOWN_DISPLAY_DEVICE@:<br />
      <p>
        Le périphérique d'affichage est introuvable ou impossible à ouvrir.<br />
      </p>
    </li>
    <li>
      $CENOMEM@:<br />
      <p>
        La structure de fenêtre ou la fenêtre de rendu sous-jacente n'a pas pu être allouée.<br />
      </p>
    </li>
  </ul>
  <br />
  <p>
    Cette fonction écrit des entrées de log dans le domaine $L"window"@ lorsque la fenêtre est ouverte ou lorsque la création échoue.
  </p>
</div>
<hr />

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>$Sbunny_start_style@</li>
    <li>$Sbunny_stop@</li>
    <li>$Sbunny_get_fullscreen_modes@</li>
    <li>$Sbunny_get_screen_resolution@</li>
  </ul>
</div>
