<?php
// Generated by generate_doc.php; do not edit manually.
if (!isset($functions)) $functions = [];
if (!isset($circle_level)) $circle_level = [];
if (!isset($version_that_support)) $version_that_support = [];

$functions[120] = array_values(array_unique(array_merge($functions[120] ?? [], [
  'bunny_start',
])));

foreach ([
  'bunny_start' => 0,
] as $k => $v) $circle_level[$k] = $v;

foreach ([
  'bunny_start' => [0, $latest_version],
] as $k => $v) $version_that_support[$k] = $v;
