<?php
// Generated by generate_doc.php; do not edit manually.
if (!isset($functions)) $functions = [];
if (!isset($circle_level)) $circle_level = [];
if (!isset($version_that_support)) $version_that_support = [];

$functions[100] = array_values(array_unique(array_merge($functions[100] ?? [], [
  't_bunny_window',
])));
$functions[105] = array_values(array_unique(array_merge($functions[105] ?? [], [
  't_bunny_window_style',
])));
$functions[120] = array_values(array_unique(array_merge($functions[120] ?? [], [
  'bunny_start',
])));
$functions[140] = array_values(array_unique(array_merge($functions[140] ?? [], [
  'bunny_stop',
])));
$functions[160] = array_values(array_unique(array_merge($functions[160] ?? [], [
  'bunny_display',
])));
$functions[180] = array_values(array_unique(array_merge($functions[180] ?? [], [
  'bunny_get_screen_resolution',
])));
$functions[190] = array_values(array_unique(array_merge($functions[190] ?? [], [
  'bunny_get_fullscreen_modes',
])));
$functions[200] = array_values(array_unique(array_merge($functions[200] ?? [], [
  'bunny_start_style',
])));
$functions[220] = array_values(array_unique(array_merge($functions[220] ?? [], [
  'bunny_set_key_repeat',
])));
$functions[240] = array_values(array_unique(array_merge($functions[240] ?? [], [
  'bunny_set_mouse_visibility',
])));
$functions[260] = array_values(array_unique(array_merge($functions[260] ?? [], [
  'bunny_set_mouse_position_window',
])));
$functions[280] = array_values(array_unique(array_merge($functions[280] ?? [], [
  'bunny_set_mouse_position',
])));
$functions[300] = array_values(array_unique(array_merge($functions[300] ?? [], [
  'bunny_request_focus',
])));
$functions[320] = array_values(array_unique(array_merge($functions[320] ?? [], [
  'bunny_move_window',
])));
$functions[330] = array_values(array_unique(array_merge($functions[330] ?? [], [
  'bunny_get_window_position',
])));
$functions[340] = array_values(array_unique(array_merge($functions[340] ?? [], [
  'bunny_resize_window',
])));
$functions[350] = array_values(array_unique(array_merge($functions[350] ?? [], [
  'bunny_vertical_sync',
])));
$functions[360] = array_values(array_unique(array_merge($functions[360] ?? [], [
  'bunny_set_window_icon',
])));
$functions[400] = array_values(array_unique(array_merge($functions[400] ?? [], [
  'bunny_begin',
])));
$functions[410] = array_values(array_unique(array_merge($functions[410] ?? [], [
  'bunny_beginc',
])));
$functions[420] = array_values(array_unique(array_merge($functions[420] ?? [], [
  'bunny_begin_configuration',
])));
$functions[430] = array_values(array_unique(array_merge($functions[430] ?? [], [
  'bunny_end',
])));
$functions[440] = array_values(array_unique(array_merge($functions[440] ?? [], [
  'bunny_single_fullscreen',
])));
$functions[450] = array_values(array_unique(array_merge($functions[450] ?? [], [
  'bunny_all_fullscreen',
])));
$functions[460] = array_values(array_unique(array_merge($functions[460] ?? [], [
  'bunny_get_monitors_origin',
])));
$functions[470] = array_values(array_unique(array_merge($functions[470] ?? [], [
  'bunny_list_monitors',
])));
$functions[480] = array_values(array_unique(array_merge($functions[480] ?? [], [
  'bunny_list_autonomous_monitors',
])));

foreach ([
  't_bunny_window' => 0,
  't_bunny_window_style' => 20,
  'bunny_start' => 0,
  'bunny_stop' => 0,
  'bunny_display' => 0,
  'bunny_get_screen_resolution' => 20,
  'bunny_get_fullscreen_modes' => 20,
  'bunny_start_style' => 20,
  'bunny_set_key_repeat' => 10,
  'bunny_set_mouse_visibility' => 20,
  'bunny_set_mouse_position_window' => 20,
  'bunny_set_mouse_position' => 20,
  'bunny_request_focus' => 20,
  'bunny_move_window' => 20,
  'bunny_get_window_position' => 20,
  'bunny_resize_window' => 20,
  'bunny_vertical_sync' => 30,
  'bunny_set_window_icon' => 30,
  'bunny_begin' => 20,
  'bunny_beginc' => 20,
  'bunny_begin_configuration' => 20,
  'bunny_end' => 20,
  'bunny_single_fullscreen' => 30,
  'bunny_all_fullscreen' => 30,
  'bunny_get_monitors_origin' => 30,
  'bunny_list_monitors' => 30,
  'bunny_list_autonomous_monitors' => 30,
] as $k => $v) $circle_level[$k] = $v;

foreach ([
  't_bunny_window' => [0, $latest_version],
  't_bunny_window_style' => [3, $latest_version],
  'bunny_start' => [0, $latest_version],
  'bunny_stop' => [0, $latest_version],
  'bunny_display' => [0, $latest_version],
  'bunny_get_screen_resolution' => [9, $latest_version],
  'bunny_get_fullscreen_modes' => [11, $latest_version],
  'bunny_start_style' => [3, $latest_version],
  'bunny_set_key_repeat' => [6, $latest_version],
  'bunny_set_mouse_visibility' => [6, $latest_version],
  'bunny_set_mouse_position_window' => [6, $latest_version],
  'bunny_set_mouse_position' => [6, $latest_version],
  'bunny_request_focus' => [6, $latest_version],
  'bunny_move_window' => [9, $latest_version],
  'bunny_get_window_position' => [13, $latest_version],
  'bunny_resize_window' => [9, $latest_version],
  'bunny_vertical_sync' => [12, $latest_version],
  'bunny_set_window_icon' => [13, $latest_version],
  'bunny_begin' => [13, $latest_version],
  'bunny_beginc' => [13, $latest_version],
  'bunny_begin_configuration' => [13, $latest_version],
  'bunny_end' => [13, $latest_version],
  'bunny_single_fullscreen' => [13, $latest_version],
  'bunny_all_fullscreen' => [13, $latest_version],
  'bunny_get_monitors_origin' => [13, $latest_version],
  'bunny_list_monitors' => [13, $latest_version],
  'bunny_list_autonomous_monitors' => [13, $latest_version],
] as $k => $v) $version_that_support[$k] = $v;
