<div class="prototype">
  $Ktypedef struct@ $Ts_bunny_sound_slice@<br />
  {<br />
  $A $Tt_bunny_sound@ $Ssound@;<br />
  $A $Tuint64_t@ $Sid@;<br />
  $A $Tdouble@ $Sindex@;<br />
  $A $Tdouble@ $Sduration@;<br />
  $A $Tdouble@ $Sactive_duration@;<br />
  <br />
  } $Tt_bunny_sound_slice@;<br />
</div>
<hr />

<div class="resume">
  <h3>Description</h3>
  $A The sound slice structure is used by the field $Ssound_areas@ of
  $Tt_bunny_sound_sprite@ and contains several information.<br />
  <br />
  First: it contains the subpart of the music file that is used by
  the sound sprite, with $Sindex@ and $Sduration@. It also contains
  the $Sactive_duration@ which is the length of the slice which is
  loaded with meaning: for example, a character is talking in an heavily
  echoed place and you want to animate its mouth: the $Sactive_duration@
  is the part of moving the character's mouth is cool. The remaning
  part between $Sactive_duration@ and $Sduration@ would be filled with
  echoes only.<br />
  <br />
  It also contains the id for internal purpose: the name of the slice
  from the configuration file, hashed with bunny_sound_sprite_slice_name.
  Finally, it contains a $Ssound@ field which contains tweaking information
  to read the sound as you desire: with a pitch, a volume, a placement, etc.
</div>
<hr />

<div class="parameters">
  <h3>Attributes</h3>
  <ul>
    <li>
      $Tt_bunny_sound@ $Ssound@:<br />
      $A Pitch, volume, position, etc. information about the way
      the slice must be read.
    </li>
    <li>
      $Tuint64_t@ $Sid@:<br />
      $A The id of the slice, generated by bunny_sound_sprite_slice_name with
      the name of the slice written in the sound sprite configuration file
      as input.
    </li>
    <li>
      $Tdouble@ $Sindex@:<br />
      $A In seconds. Where does the slice start in file?
    </li>
    <li>
      $Tdouble@ $Sduration@:<br />
      $A In seconds. Which duration for the current slice in file?
      Note that this value is the duration at pitch 1.0: any change in pitch
      will automatically recompute the correct duration.
    </li>
    <li>
      $Tdouble@ $Sactive_duration@:<br />
      $A The active duration of the slice, used by bunny_sound_sprite_is_talking.
    </li>
  </ul>
</div>

<div class="related_functions">
  <h3>Related functions</h3>
  <ul>
    <li>t_bunny_sound_sprite</li>
    <li>bunny_load_sound_sprite</li>
  </ul>
</div>

